export const ROUTE_MODES=['SHORTEST','ACCESSIBLE','BIKE_ONLY'];
export function normalizeKakaoRoute(data,mode){
 if(data.status!=='OK'||!data.route)throw new Error('자전거 경로를 찾지 못했어요. 출발지와 목적지를 확인해 주세요.');
 const props=data.route.properties,steps=data.route.legs?.flatMap(l=>l.steps)||[],path=[];
 for(const s of steps)for(const p of s.path?.points||[]){if(!Array.isArray(p)||p.length<2||!p.every(Number.isFinite)||Math.abs(p[0])>180||Math.abs(p[1])>90)throw new Error('경로 좌표 형식이 올바르지 않아요.');const prev=path.at(-1);if(!prev||prev.lng!==p[0]||prev.lat!==p[1])path.push({lng:p[0],lat:p[1]});}
 if(path.length<2||!Number.isFinite(props?.totalTime)||props.totalTime<=0||!Number.isFinite(props.totalDistance)||props.totalDistance<=0)throw new Error('경로 응답이 불완전해요.');
 let landingUrl=null;try{const u=new URL(props.landingUrl);if(u.protocol==='https:'&&u.hostname==='map.kakao.com')landingUrl=u.href;}catch{}
 return {id:mode,routeMode:mode,path,distance:props.totalDistance,minutes:Math.ceil(props.totalTime/60),seconds:props.totalTime,landingUrl,steps:steps.map(s=>({text:s.properties?.guidance||'',distance:s.properties?.distance,time:s.properties?.time})),risk:null,hotspotIds:[],hotspots:null,bikeRoadShare:null,source:'KAKAO bicycle API'};
}
export function createKakaoProvider({base,fetcher=fetch}){return {async routes(origin,destination,signal){if(!base)throw new Error('자전거 경로 서버가 아직 연결되지 않았어요. 다른 이동수단을 선택하거나 잠시 후 다시 시도해 주세요.');return Promise.all(ROUTE_MODES.map(async mode=>{const q=new URLSearchParams({start_x:origin.lng,start_y:origin.lat,end_x:destination.lng,end_y:destination.lat,route_mode:mode});const r=await fetcher(base+'/api/routing/bicycle?'+q,{signal:signal||AbortSignal.timeout(15000)});let d;try{d=await r.json();}catch{throw new Error('자전거 경로 서버가 아직 연결되지 않았어요.');}if(!r.ok)throw new Error(d.error||'경로를 조회하지 못했어요.');return normalizeKakaoRoute(d,mode);}));},async hotspots(bounds,signal){const r=await fetcher(base+'/api/orbit/hotspots?bbox='+bounds.join(','),{signal:signal||AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||d.coverage!==true||!Array.isArray(d.features))throw new Error('사고 데이터가 연결되지 않아 안전 경로 평가는 사용할 수 없어요.');return d;}};}
