// Ported from uploaded ORBIT Bike server.py: bicycle costing + polyline6 + maneuvers.
import {nearestInventoryRoad} from './bikeRoadInventory.js';
import {createKakaoProvider} from './routeProvider.js';
export const VALHALLA_URL='https://valhalla1.openstreetmap.de/route';
export function decodePolyline6(encoded){let index=0,lat=0,lng=0,points=[];while(index<encoded.length){const read=()=>{let result=0,shift=0,b;do{if(index>=encoded.length||shift>30)throw new Error('경로 좌표를 읽지 못했어요.');b=encoded.charCodeAt(index++)-63;if(b<0||b>63)throw new Error('경로 좌표 형식이 올바르지 않아요.');result|=(b&31)<<shift;shift+=5;}while(b>=32);return result&1?~(result>>1):result>>1;};lat+=read();lng+=read();points.push({lat:lat/1e6,lng:lng/1e6});}return points;}
export function normalizeValhalla(data,mode){const trip=data.trip;if(!trip?.legs?.length||!Number.isFinite(trip.summary?.time)||trip.summary.time<=0||trip.units!=='kilometers')throw new Error('자전거 경로를 찾지 못했어요.');const path=[],steps=[];for(const leg of trip.legs){const points=decodePolyline6(leg.shape||'');let offset=path.length;if(path.length&&points.length&&path.at(-1).lat===points[0].lat&&path.at(-1).lng===points[0].lng){points.shift();offset--;}path.push(...points);for(const m of leg.maneuvers||[])steps.push({text:m.instruction||'경로를 따라 이동하세요.',distance:Math.round((m.length||0)*1000),time:m.time,beginIndex:Math.max(0,offset+(m.begin_shape_index||0)),endIndex:Math.max(0,offset+(m.end_shape_index||0)),turnType:m.type});}if(path.length<2||path.some(p=>!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||Math.abs(p.lat)>90||Math.abs(p.lng)>180))throw new Error('경로 좌표가 불완전해요.');return {id:'ORBIT-'+mode,routeMode:mode,path,steps,seconds:trip.summary.time,minutes:Math.ceil(trip.summary.time/60),distance:Math.round(trip.summary.length*1000),risk:null,hotspotIds:[],hotspots:null,bikeRoadShare:null,source:'Valhalla / OpenStreetMap',provider:'ORBIT',landingUrl:null};}
export function valhallaPayload(origin,destination,mode,polygons=[]){const quick=mode==='SHORTEST';return {locations:[{lat:origin.lat,lon:origin.lng},{lat:destination.lat,lon:destination.lng}],costing:'bicycle',costing_options:{bicycle:{bicycle_type:quick?'road':'hybrid',cycling_speed:quick?22:18,use_roads:quick?.55:mode==='BIKE_ONLY'?.05:.18,use_hills:quick?.45:.25}},units:'kilometers',language:'ko-KR',...(polygons.length?{exclude_polygons:polygons}:{})};}
export function createOrbitProvider({base='',fetcher=fetch}={}){const external=import.meta.env?.VITE_ORBIT_ROUTING_URL||VALHALLA_URL;let lastRequest=0;async function request(origin,destination,mode,signal,polygons=[]){const wait=Math.max(0,1050-(Date.now()-lastRequest));if(wait)await new Promise((resolve,reject)=>{const cancel=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',cancel);resolve();},wait);signal?.addEventListener('abort',cancel,{once:true});});if(signal?.aborted)throw new DOMException('Aborted','AbortError');lastRequest=Date.now();let r;try{r=await fetcher(external,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(valhallaPayload(origin,destination,mode,polygons)),signal:signal||AbortSignal.timeout(25000)});}catch(e){if(e.name==='AbortError')throw e;throw new Error('ORBIT 경로 서버에 연결하지 못했어요. 잠시 후 다시 시도해 주세요.');}if(!r.ok)throw new Error('ORBIT 경로 조회가 지연되고 있어요. 다시 시도해 주세요.');return normalizeValhalla(await r.json(),mode);}
 return {kind:'ORBIT',async routes(origin,destination,signal){const out=[];for(const mode of ['SHORTEST','ACCESSIBLE','BIKE_ONLY'])out.push(await request(origin,destination,mode,signal));return out;},async roadInventory(point,signal){const r=await fetcher(import.meta.env.BASE_URL+'data/orbit-bike-roads.json',{signal});if(!r.ok)return null;const d=await r.json();return {nearest:nearestInventoryRoad(d.roads,point),source:d.source};},async hotspots(bounds,signal){if(!base)throw new Error('공개 사고 데이터 서버가 연결되지 않아 사고구간 회피 분석을 사용할 수 없어요.');return createKakaoProvider({base,fetcher}).hotspots(bounds,signal);},async avoid(origin,destination,features,signal){const chosen=features.slice(0,10);const rings=chosen.flatMap(f=>f.geometry.type==='Polygon'?[f.geometry.coordinates[0]]:f.geometry.coordinates.map(p=>p[0]));const route=await request(origin,destination,'BIKE_ONLY',signal,rings);return {...route,id:'ORBIT-AVOID',excludedIds:chosen.map(f=>f.id)};}};
}
