import test from 'node:test';
import assert from 'node:assert/strict';
import {eligibleOffer,rankNearbyMerchants} from '../src/commerce/liveMerchants.js';
import {pickupCandidates} from '../src/mobility/taxiPickup.js';
const now=Date.parse('2026-10-06T18:00:00+09:00'),arrival=now+20*60000,place={id:'kakao-123',name:'실제 매장',lat:37.5,lng:127,kind:'카페'};
const offer={placeId:place.id,verified:true,title:'도착 할인',terms:'시간 내 방문',discountPercent:15,validFrom:'2026-10-06T00:00:00+09:00',validUntil:'2026-10-07T00:00:00+09:00',startTime:'18:00',endTime:'19:00'};
test('unverified, expired, wrong store and out-of-window benefits are never attached',()=>{assert.equal(eligibleOffer(place,arrival,[{...offer,verified:false}],now),null);assert.equal(eligibleOffer(place,arrival,[{...offer,placeId:'other'}],now),null);assert.equal(eligibleOffer(place,arrival,[{...offer,validUntil:'2020-01-01'}],now),null);assert.equal(eligibleOffer(place,arrival+3600000,[offer],now),null);assert.equal(eligibleOffer(place,arrival,[{...offer,redeemUrl:'javascript:alert(1)'}],now),null);assert.equal(eligibleOffer(place,arrival,[offer],now),offer);});
test('presentation benefits preserve live identity and explicitly mark generated merchant data',()=>{const rows=rankNearbyMerchants([place],{destination:place,estimatedArrivalTime:Date.now()},'all');assert.equal(rows[0].name,place.name);assert.equal(rows[0].lat,place.lat);assert.equal(rows[0].isPresentation,true);assert.equal(rows[0].offer.isDemo,true);assert.ok(rows[0].benefitLabel);assert.ok(rows[0].price>0);});
test('live merchant matching follows destination and category',()=>{const j={destination:place,estimatedArrivalTime:arrival};assert.equal(rankNearbyMerchants([place,{...place,id:'far',lat:37.51}],j)[0].id,place.id);assert.equal(rankNearbyMerchants([place],j,'음식점').length,0);assert.equal(rankNearbyMerchants([place],{...j,estimatedArrivalTime:null}).length,0);});
test('taxi pickup prefers actual ranks and excludes bridges, tunnels and inaccessible roads',()=>{const elements=[{id:1,lat:37.501,lon:127,tags:{amenity:'taxi',name:'역 앞 승강장'}},{id:2,tags:{highway:'secondary',name:'큰길'},geometry:[{lat:37.5,lon:126.999},{lat:37.5,lon:127.001}]},...['bridge','tunnel'].map((key,i)=>({id:3+i,tags:{highway:'primary',name:key,[key]:'yes'},geometry:[{lat:37.5,lon:127},{lat:37.51,lon:127}]}))];const rows=pickupCandidates(elements,place);assert.equal(rows.length,2);assert.equal(rows[0].kind,'taxi-rank');assert.equal(rows[1].name,'큰길 인근');assert.equal(rows[1].lat,37.5);});

import {presentationMerchant} from '../src/commerce/presentationBenefits.js';
import {rankPickups} from '../src/mobility/pickupRecommendation.js';
test('generated benefits stay stable across filters and include gift and cashback cases',()=>{const rows=Array.from({length:30},(_,i)=>presentationMerchant({...place,id:`kakao-${i}`}));assert.ok(rows.some(m=>m.reward));assert.ok(rows.some(m=>m.cashbackPercent>0));for(const m of rows){assert.deepEqual(presentationMerchant(m),m);assert.ok(m.cashbackPercent>=0&&m.cashbackPercent<=12);}});
test('pickup price and walking modes genuinely rank differently and return estimate provenance',()=>{const destination={lat:37.5,lng:127.08};const rows=[{id:'near',name:'가까운 큰길',lat:37.5,lng:127,distance:50},{id:'cheap',name:'목적지 방향 큰길',lat:37.5,lng:127.01,distance:500}];assert.equal(rankPickups(rows,destination,'price',now)[0].id,'cheap');assert.equal(rankPickups(rows,destination,'walk',now)[0].id,'near');assert.equal(rankPickups(rows,destination)[0].fareSource,'MVP distance model');});
