import test from 'node:test';
import assert from 'node:assert/strict';
import {humanEta,defaultContext,bikeRoutes,bikeCost,selectBikeRoute} from '../src/mobility/mobilityEngine.js';
import {demoClock,demoMerchants,DEMO_DESTINATION} from '../src/demoMerchants.js';
import {rankMerchants,formatTime} from '../src/arrivalEngine.js';
import {demoRobots} from '../src/data/demoRobots.js';
import {dispatchRobot} from '../src/physical/robotDispatchEngine.js';
const now=demoClock(),origin={lat:37.5445,lng:127.0374},destination=DEMO_DESTINATION;
const fixtureAnalysis={status:'ready',options:[{id:'a',type:'FAST',minutes:29,risk:12},{id:'b',type:'BALANCED',minutes:31,risk:8},{id:'c',type:'SAFE',minutes:33,risk:2}]};
const eta=(mode,patch={})=>humanEta({origin,destination,mode,departureTime:now,context:{...defaultContext(),bikeAnalysis:fixtureAnalysis,...patch},demo:true});
const merchants=demoMerchants(destination),robots=demoRobots(now);
test('five modes normalize distinct human ETA',()=>{assert.equal(new Set(['taxi','car','transit','bike','walk'].map(m=>eta(m).humanArrivalETA)).size,5);assert.equal(formatTime(eta('taxi').humanArrivalETA),'18:47');});
test('transit chooses catchable train; missed train changes all downstream',()=>{const a=eta('transit'),b=eta('transit',{missedTrains:1});assert.equal(a.route.nextTrain,7);assert.equal(formatTime(a.humanArrivalETA),'18:51');assert.equal(formatTime(b.humanArrivalETA),'18:59');const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:b.humanArrivalETA,now,previous:p});assert.equal(p.robotId,'R1');assert.equal(q.robotId,'R2');assert.ok(q.prepStart>p.prepStart);assert.equal(q.gap,0);});
test('bike safety changes ETA, deal, ranking and dispatch',()=>{const a=eta('bike'),b=eta('bike',{bikeRoute:'SAFE'});assert.equal(formatTime(a.humanArrivalETA),'18:52');assert.equal(formatTime(b.humanArrivalETA),'18:56');assert.ok(fixtureAnalysis.options[2].risk<fixtureAnalysis.options[0].risk);assert.equal(rankMerchants(merchants,a)[0].id,'demo-coffee');assert.notEqual(rankMerchants(merchants,b)[0].id,'demo-coffee');assert.equal(rankMerchants(merchants,b).find(m=>m.id==='demo-coffee').discount,0);const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:b.humanArrivalETA,now,previous:p});assert.equal(q.robotId,'R2');assert.equal(q.gap,0);});
test('traffic delay releases R1, holds preparation and reserves R2',()=>{const a=eta('taxi'),b=eta('taxi',{trafficDelay:11});const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:b.humanArrivalETA,now,previous:p});assert.equal(p.robotId,'R1');assert.equal(p.status,'RESERVED');assert.equal(q.robotId,'R2');assert.equal(formatTime(q.handoffAt),'18:58');assert.equal(q.status,'RESERVED');assert.equal(q.gap,0);assert.match(q.events.join(' '),/RELEASED.*REASSIGNED/);});
test('started preparation is not rewound; unavailable robot is explicit',()=>{const a=eta('taxi');const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA+11*60000,now:p.prepStart+60000,previous:p});assert.equal(q.prepStart,p.prepStart);assert.equal(q.readyAt,p.readyAt);assert.equal(dispatchRobot({robots:[],merchant:merchants[0],arrival:a.humanArrivalETA,now}).status,'UNAVAILABLE');});
test('elapsed journey preserves arrival and robot reservations do not overlap',()=>{assert.equal(eta('taxi',{elapsed:10}).humanArrivalETA,eta('taxi').humanArrivalETA);const a=eta('taxi');const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now,reservations:[p]});assert.notEqual(p.robotId,q.robotId);assert.ok(q.gap>0);});

test('transit switches after elapsed travel choose a future catchable train',()=>{const j=eta('transit',{elapsed:10});assert.ok(j.route.nextTrain>=14);const boarded=eta('transit',{elapsed:10,boarded:true});assert.equal(boarded.route.nextTrain,7);});

test('bike costs use exact weights and minimize every candidate',()=>{const rs=[{id:'a',minutes:29,risk:67},{id:'b',minutes:33,risk:21}];assert.equal(bikeCost(rs[0],'FAST'),42.4);assert.equal(bikeCost(rs[1],'FAST'),37.2);for(const profile of ['FAST','BALANCED','SAFE'])assert.equal(selectBikeRoute(rs,profile).id,'b');assert.deepEqual(bikeRoutes(),[]);assert.equal(bikeCost({minutes:10,risk:0},'SAFE'),10);assert.throws(()=>bikeCost({minutes:10,risk:-1},'FAST'));assert.throws(()=>selectBikeRoute([],'FAST'));});
test('balanced route propagates to preparation and dispatch',()=>{const a=eta('bike'),b=eta('bike',{bikeRoute:'BALANCED'});assert.equal(formatTime(b.humanArrivalETA),'18:54');assert.ok(b.humanArrivalETA>a.humanArrivalETA);const p=dispatchRobot({robots,merchant:merchants[0],arrival:a.humanArrivalETA,now});const q=dispatchRobot({robots,merchant:merchants[0],arrival:b.humanArrivalETA,now,previous:p});assert.ok(q.prepStart>p.prepStart);assert.equal(q.gap,0);});
