import test from 'node:test';import assert from 'node:assert/strict';
import {humanEta} from '../src/mobility/mobilityEngine.js';
import {cleanPreferences,personalizeBike,personalizeMerchants} from '../src/personalization.js';
import {calculateMerchantScore} from '../src/arrivalEngine.js';
const origin={lat:37,lng:127},destination={lat:37.01,lng:127.02};
test('fractional GPS elapsed values never leak decimal minutes into subsequent ETA and wait',()=>{const j=humanEta({origin,destination,mode:'bike',departureTime:1000,context:{elapsed:25+2/3,bikeRoute:'FAST',bikeAnalysis:{options:[{type:'FAST',minutes:29,path:[]}]}}});assert.equal(j.etaMinutes,4);const m=calculateMerchantScore({distance:0,prepMinutes:4,currentWaitMinutes:1,discountPercent:0,congestion:'quiet',price:100,stockLevel:1}, {...j,etaMinutes:10/3});assert.equal(m.waitAfterArrival,2);});
test('walking pace changes real ETA and malformed stored preferences fall back safely',()=>{const slow=humanEta({origin,destination,mode:'walk',context:{preferences:{pace:'relaxed'}}}),fast=humanEta({origin,destination,mode:'walk',context:{preferences:{pace:'brisk'}}});assert.ok(slow.etaMinutes>fast.etaMinutes);assert.ok(Number.isInteger(slow.etaMinutes));assert.equal(cleanPreferences(null).pace,'normal');});
test('personalized speed and safety affect candidate selection without compounding adjustments',()=>{const a={id:'a',routeMode:'SHORTEST',minutes:20,seconds:1200,risk:10,path:[origin,destination],hotspotIds:['a'],overlapMeters:100};const b={...a,id:'b',routeMode:'ACCESSIBLE',minutes:31,seconds:1860,risk:5,path:[origin,{lat:37.02,lng:127.02},destination],hotspotIds:[],overlapMeters:0};const analysis={candidates:[a,b],options:[a,b]};assert.equal(personalizeBike(analysis,{safety:'fast'}).options[2].id,'a');assert.equal(personalizeBike(analysis,{safety:'safe'}).options[2].id,'b');const once=personalizeBike(analysis,{pace:'relaxed'});assert.equal(once.options[0].minutes,25);assert.equal(personalizeBike(once,{pace:'relaxed'}).options[0].minutes,25);assert.equal(personalizeBike(once,{pace:'normal'}).options[0].minutes,20);});
test('merchant preference changes ranking while leaving all filtered candidates available',()=>{const rows=[{id:'coffee',category:'카페',score:50,distance:30,cashbackPercent:8},{id:'food',category:'음식점',score:40,distance:60,reward:{name:'음료'}}];assert.equal(personalizeMerchants(rows,{} )[0].id,'coffee');const result=personalizeMerchants(rows,{category:'음식점',benefit:'gift'});assert.equal(result[0].id,'food');assert.equal(result.length,2);assert.ok(result[0].personalReason);});
