import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,Car,Package,Zap} from 'lucide-react';
import LiveMap from '../LiveMap.jsx';
import {formatTime} from '../arrivalEngine.js';
import {mobilityAdapter,robotAdapter,parkingAdapter} from '../adapters/contactAdapters.js';
import {recommendContact,simulationFrame,compareContacts,replanFromFrame,shouldPropose} from './dynamicPickupEngine.js';
import {recommendHandoff} from './handoffEngine.js';
import {parkingFixture} from './scenarios.js';
import {scheduleCharging,chargingState,chargingMetrics} from './chargingScheduler.js';
import './contact.css';
const mins=s=>Math.max(0,Math.ceil(s/60));
export default function ContactExperience({origin,destination,mapKey,onJourney,onBack}){
 const [kind,setKind]=useState('taxi'),[view,setView]=useState('compare'),[scenario,setScenario]=useState(()=>mobilityAdapter.createScenario(origin)),[choice,setChoice]=useState(null),[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[proposal,setProposal]=useState(null),[event,setEvent]=useState(''),[completed,setCompleted]=useState(null),[baseline,setBaseline]=useState(null),[offset,setOffset]=useState(0),[records,setRecords]=useState([]),[liveGps,setLiveGps]=useState(null),[gpsMessage,setGpsMessage]=useState('');
 const result=useMemo(()=>(kind==='robot'?recommendHandoff:recommendContact)(scenario),[scenario,kind]);
 const active=choice||result.recommended,frame=simulationFrame(active,elapsed),staticChoice=baseline||result.static;
 const reset=(nextKind)=>{const s=(nextKind==='robot'?robotAdapter:mobilityAdapter).createScenario(origin);setKind(nextKind);setScenario(s);setChoice(null);setElapsed(0);setRunning(false);setProposal(null);setEvent('');setBaseline(null);setOffset(0);setView('compare');setCompleted(null);setLiveGps(null);setGpsMessage('');};
 useEffect(()=>{if(!running||proposal)return;const timer=setInterval(()=>setElapsed(t=>Math.min(active.meetingSeconds,t+10)),500);return()=>clearInterval(timer);},[running,active.meetingSeconds,proposal]);
 useEffect(()=>{if(!running||!frame.completed)return;setRunning(false);const metrics=compareContacts(staticChoice,{...active,meetingSeconds:offset+elapsed});const record={kind,metrics,source:'simulation',recordedAt:Date.now()};setCompleted(record);setRecords(rs=>[record,...rs].slice(0,10));setView('complete');},[frame.completed,running,kind,active,offset,elapsed,staticChoice]);
 function accept(){setChoice(result.recommended);setBaseline(result.static);setView('moving');setRunning(true);setElapsed(0);}
 function delay(){if(proposal||frame.completed)return;const plan=replanFromFrame(scenario,active,elapsed,300);setEvent(kind==='robot'?'로봇의 통로가 혼잡해졌어요.':'차량이 예상보다 늦어지고 있어요.');setBaseline(b=>({...b,actorSeconds:b.actorSeconds+300,meetingSeconds:Math.max(b.userSeconds,b.actorSeconds+300),gapSeconds:Math.abs(b.userSeconds-b.actorSeconds-300)}));
 if(shouldPropose(plan.current,plan.recommended,scenario.minimumImprovement+scenario.switchPenalty)){setProposal({...plan,saved:plan.current.meetingSeconds-plan.recommended.meetingSeconds,at:elapsed});setEvent(kind==='robot'?'로봇의 통로가 혼잡해졌어요.':'차량이 예상보다 늦어지고 있어요.');}
 else{applyReplan(plan,plan.current,'충분한 개선이 없어 현재 만남 위치를 유지합니다.');}}
 function applyReplan(plan,next,message){const oldUserDistance=active.walking.distance*Math.min(1,elapsed/Math.max(1,active.userSeconds)),oldActorDistance=active.approach.distance*Math.min(1,elapsed/Math.max(1,active.actorSeconds));setChoice({...next,metricWalk:(active.metricWalkOffset||0)+oldUserDistance+next.walking.distance,metricApproach:(active.metricApproachOffset||0)+oldActorDistance+next.approach.distance,metricWalkOffset:(active.metricWalkOffset||0)+oldUserDistance,metricApproachOffset:(active.metricApproachOffset||0)+oldActorDistance,metricUserSeconds:offset+elapsed+next.userSeconds,metricActorSeconds:offset+elapsed+next.actorSeconds});setScenario(plan.scenario);setOffset(t=>t+elapsed);setElapsed(0);setEvent(message);}
 function resolveProposal(accepted){applyReplan(proposal,accepted?proposal.recommended:proposal.current,accepted?'새 만남 위치로 안내합니다.':'현재 위치에서 만나기로 했어요.');setProposal(null);}
 function locate(){if(!navigator.geolocation){setGpsMessage('GPS를 사용할 수 없어 이동 시뮬레이션을 이어갑니다.');return;}navigator.geolocation.getCurrentPosition(p=>{setLiveGps({lat:p.coords.latitude,lng:p.coords.longitude});setGpsMessage('실제 위치를 지도에 표시합니다. 만남 계산은 동일한 시뮬레이션을 유지합니다.');},()=>setGpsMessage('위치 권한 없이도 이동 시뮬레이션을 이어갑니다.'),{timeout:10000});}
 if(view==='charging')return <ChargingExperience onBack={()=>setView('complete')}/>;
 const markers=[{...frame.user,id:'person',name:'사용자',kind:'person'},{...frame.actor,id:'vehicle',name:kind==='robot'?'로봇 R1':'차량',kind:'actor'},{...scenario.nodes.u,id:'fixed',name:kind==='robot'?'기존 수령지':'기존 승차지',kind:'fixed'},{...scenario.nodes[active.id],id:'recommended',name:kind==='robot'?'추천 전달 위치':'추천 승차 위치',kind:'recommended'},...(liveGps?[{...liveGps,id:'gps-live',name:'GPS 현재 위치',kind:'person'}]:[])];
 return <main className="contact-page"><div className="contact-title"><span>Demo Mode</span><p>{kind==='robot'?'ROBOT HANDOFF':'DYNAMIC PICKUP'}</p><h1>{view==='poc'?'만남 비교 결과':view==='complete'?(kind==='robot'?'물품을 받았어요':'차량과 만났어요'):view==='moving'?'서로를 향해 이동 중':kind==='robot'?'어디에서 받을까요?':'어디에서 만날까요?'}</h1></div>
 {['compare','moving'].includes(view)&&<><div className="contact-map"><LiveMap center={origin} places={[]} onSelect={()=>{}} onMove={()=>{}} kakaoKey={mapKey} onError={()=>{}} contactMarkers={markers} routeVariants={[{path:active.walking.path,color:'#378453'},{path:active.approach.path,color:'#262a2c'}]} routePath={active.approach.path}/></div><div className="contact-legend"><span>● 사용자</span><span>● {kind==='robot'?'로봇':'차량'}</span><span>□ 기존</span><span>◆ 추천</span></div></>}
 {view==='compare'&&<section className="contact-action"><p className="contact-line">{kind==='robot'?'기존 수령지까지':'지금 자리에서 타면'} 약 {mins(result.static.meetingSeconds)}분</p><h2>{Math.round(active.walking.distance)}m 걸어가면<br/><strong>약 {mins(active.meetingSeconds)}분</strong></h2><p className="contact-reason">약 {Math.max(0,Math.round((result.static.meetingSeconds-active.meetingSeconds)/60))}분 빠르게 {kind==='robot'?'받을':'탈'} 수 있어요</p><button className="arrival-primary" onClick={accept}>걸어가며 만나기<ArrowRight size={20}/></button><details><summary>추천 위치 비교</summary>{result.candidates.map(c=><p key={c.id}>{c.name} · 보행 {mins(c.userSeconds)}분 / 접근 {mins(c.actorSeconds)}분 / 만남 {mins(c.meetingSeconds)}분</p>)}</details></section>}
 {view==='moving'&&<section className="contact-action"><p>{active.name}에서 만나요</p><h2><strong>{mins(proposal?proposal.current.meetingSeconds:frame.remainingSeconds)}분</strong> 뒤 만남</h2><div className="contact-progress"><progress aria-label="접점 이동 진행률" max={active.meetingSeconds} value={elapsed}/></div><p className="contact-line">사용자 {mins(Math.max(0,active.userSeconds-elapsed))}분 · {kind==='robot'?'로봇':'차량'} {mins(Math.max(0,active.actorSeconds-elapsed))}분</p>{event&&<p className="contact-reason" role="status">{event}</p>}{proposal?<div className="contact-proposal"><h3>{Math.round(proposal.recommended.walking.distance)}m 앞에서 만나면<br/>약 {Math.round(proposal.saved/60)}분 빨라집니다</h3><button className="arrival-primary" onClick={()=>resolveProposal(true)}>새 위치에서 만나기</button><button className="arrival-secondary" onClick={()=>resolveProposal(false)}>현재 위치 유지</button></div>:<><button className="arrival-secondary" onClick={()=>setRunning(v=>!v)}>{running?'잠시 멈추기':'이동 계속하기'}</button><button className="arrival-secondary" onClick={delay}>{kind==='robot'?'통로 혼잡 발생':'차량 접근 지연'}</button></>}<details><summary>위치 연결</summary><button className="arrival-secondary" onClick={locate}>실제 GPS 위치 표시</button><p>{gpsMessage||'이동 경로는 재현 가능한 시뮬레이션입니다.'}</p></details></section>}
 {view==='complete'&&completed&&<section className="contact-action"><div className="contact-success"><Check size={38}/></div><h2>{Math.round(completed.metrics.dynamicSeconds)}초 만에<br/>{kind==='robot'?'물품 전달 완료':'승차 완료'}</h2><p className="contact-reason">{active.name}에서 함께 도착했어요.</p>{kind==='taxi'&&<button className="arrival-primary" onClick={()=>onJourney({pickup:{...scenario.nodes[active.id],name:active.name},pickupSeconds:completed.metrics.dynamicSeconds})}>{destination.name}로 출발<ArrowRight size={20}/></button>}<button className="arrival-secondary" onClick={()=>setView('poc')}>PoC 결과 보기</button><div className="contact-extension"><h3>같은 기술이 다른 이동에도 적용됩니다</h3><button onClick={()=>reset('robot')}>사용자와 로봇이 만나기<Package size={20}/></button><button onClick={()=>setView('charging')}>충전장치가 차량으로 찾아가기<Zap size={20}/></button></div><button className="arrival-text-button" onClick={()=>reset(kind)}>다시 만나기</button></section>}
 {view==='poc'&&completed&&<section className="contact-action"><h2>고정 접점과 비교했어요</h2><div className="poc-highlight"><strong>승차시간 {completed.metrics.reductionPercent}% 감소</strong><p>접근거리 {completed.metrics.approachReduction}m 감소</p><p>추가 보행 {completed.metrics.additionalWalking}m</p></div><table><thead><tr><th>측정</th><th>Static</th><th>Dynamic</th></tr></thead><tbody>{[['만남 시간',completed.metrics.staticSeconds,completed.metrics.dynamicSeconds,'초'],['접근거리',completed.metrics.staticApproach,completed.metrics.dynamicApproach,'m'],['보행시간',completed.metrics.staticWalkSeconds,completed.metrics.dynamicWalkSeconds,'초'],['도착 차이',completed.metrics.staticGap,completed.metrics.dynamicGap,'초']].map(([label,a,b,u])=><tr key={label}><th>{label}</th><td>{Math.round(a)}{u}</td><td>{Math.round(b)}{u}</td></tr>)}</tbody></table><p>현재 이동 시뮬레이션에서 계산한 결과입니다.</p><button className="arrival-primary" onClick={()=>setView('complete')}>만남 결과로 돌아가기</button></section>}
 <button className="arrival-text-button" onClick={()=>{setRunning(false);onBack();}}>목적지 설정으로 돌아가기</button></main>;
}
function ChargingExperience({onBack}){
 const [parked,setParked]=useState(false),[requested,setRequested]=useState(false),[multi,setMulti]=useState(false),[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[admin,setAdmin]=useState(false);
 const lot=useMemo(()=>parkingAdapter.locateVehicle(),[]),jobs=useMemo(()=>scheduleCharging(multi?lot.vehicles:[lot.vehicles[0]],lot.modules),[multi,lot]),own=jobs.find(j=>j.id==='내 차량'),state=requested?chargingState(own,elapsed):parked?'차량 위치 확인 완료':'차량을 주차해 주세요',allComplete=requested&&jobs.every(j=>elapsed>=j.completeAt);
 useEffect(()=>{if(!running||allComplete)return;const timer=setInterval(()=>setElapsed(t=>t+(t<30?1:30)),500);return()=>clearInterval(timer);},[running,allComplete]);
 const modulePosition=(job)=>{if(elapsed<job.assignedAt)return job.path[0];if(elapsed>=job.startAt)return job.path.at(-1);let d=Math.max(0,elapsed-job.assignedAt)/Math.max(1,job.startAt-job.assignedAt-15)*job.travelMeters/parkingFixture.scaleMeters;for(let i=1;i<job.path.length;i++){const a=job.path[i-1],b=job.path[i],len=Math.hypot(a.x-b.x,a.y-b.y);if(d<=len){const f=len?d/len:1;return {x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f};}d-=len;}return job.path.at(-1);};
 const metrics=chargingMetrics(jobs);
 return <main className="contact-page"><div className="contact-title"><span>Demo Mode</span><p>ACTIVE CHARGING</p><h1>{state}</h1></div><div className="parking-map"><svg viewBox="0 0 520 360" role="img" aria-label="실내 주차장과 충전 모듈 이동"><rect width="520" height="360" fill="#f8f9fa"/><path d="M30 180H490" stroke="#e3e6e8" strokeWidth="55"/>{[80,230].flatMap(y=>[80,180,280,380].map(x=><rect key={`${x}-${y}`} x={x} y={y} width="85" height="65" rx="8" fill="white" stroke="#bfc6cc"/>))}<text x="14" y="170" fontSize="17">출입구</text>{requested&&jobs.map(j=><polyline key={j.id} points={j.path.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#c0a900" strokeWidth="4" strokeDasharray="7 5"/>)}{parked&&(multi?lot.vehicles:[lot.vehicles[0]]).map(v=><g key={v.id}><rect x={v.x-25} y={v.y-18} width="50" height="36" rx="9" fill={v.id==='내 차량'?'#24292c':'#747c82'}/><text x={v.x} y={v.y+37} textAnchor="middle" fontSize="17">{v.id} {Math.round(v.battery+Math.max(0,Math.min(1,(elapsed-(jobs.find(j=>j.id===v.id)?.startAt||Infinity))/(jobs.find(j=>j.id===v.id)?.chargeSeconds||1)))*(v.targetBattery-v.battery))}%</text></g>)}{lot.modules.map(m=>{const assigned=jobs.filter(j=>j.moduleId===m.id&&j.assignedAt<=elapsed).at(-1),p=requested&&assigned?modulePosition(assigned):m;return <g key={m.id}><rect x={p.x-15} y={p.y-15} width="30" height="30" rx="7" fill="#fee500" stroke="#24292c"/><text x={p.x} y={p.y-23} textAnchor="middle" fontSize="16">{m.id}</text></g>;})}</svg></div><section className="contact-action">{!parked?<button className="arrival-primary" onClick={()=>setParked(true)}>이 위치에 주차하기</button>:!requested?<><p className="contact-reason">충전장치가 내 차량으로 찾아옵니다.</p><button className="arrival-primary" onClick={()=>{setRequested(true);setRunning(true);}}>자동충전 신청</button><button className="arrival-secondary" onClick={()=>setMulti(v=>!v)}>{multi?'내 차량만 신청':'여러 차량 동시 신청'}</button>{multi&&<p>다음 출차 예정 차량을 먼저 충전합니다.</p>}</>:<><h2>{own.moduleId} · {Math.round(own.energyKwh)} kWh</h2><progress aria-label="충전 진행률" value={Math.max(0,elapsed-own.startAt)} max={own.chargeSeconds}/>{multi&&<p className="contact-reason">다음 출차 예정 차량을 먼저 충전합니다.</p>}{allComplete?<><p>요청한 차량의 충전을 모두 완료했어요.</p><button className="arrival-primary" onClick={onBack}>만남 결과로 돌아가기</button></>:<><button className="arrival-secondary" onClick={()=>setRunning(v=>!v)}>{running?'잠시 멈추기':'충전 계속하기'}</button><button className="arrival-secondary" onClick={()=>setElapsed(t=>Math.min(Math.max(...jobs.map(j=>j.completeAt)),t+120))}>2분 경과</button></>}<button className="arrival-secondary" onClick={()=>setAdmin(v=>!v)}>{admin?'관리자 결과 닫기':'관리자 결과 보기'}</button>{admin&&<section className="charging-admin"><h3>충전 운영 결과</h3><p>모듈 이동거리 {metrics.totalTravel}m</p><p>8시간 예상 처리량 {metrics.dailyThroughput}대</p>{jobs.map(j=><p key={j.id}>{j.id} · 출차 {j.departureMinutes}분 후 · 대기 {mins(j.waitSeconds)}분 · {chargingState(j,elapsed)}</p>)}</section>}</>}<button className="arrival-text-button" onClick={onBack}>만남 결과로 돌아가기</button></section></main>;
}
