import React,{useEffect,useMemo,useState} from 'react';
import {parkingFixture} from './parkingData.js';
import {scheduleCharging,chargingState,chargingMetrics} from './chargingScheduler.js';
import './charging.css';
const mins=s=>Math.max(0,Math.ceil(s/60));
const parkingAdapter={locateVehicle:()=>({...structuredClone(parkingFixture),positionSource:'SIMULATED_BLE',gpsAvailable:false})};
export default function ChargingExperience({onBack}){
 const [parked,setParked]=useState(false),[requested,setRequested]=useState(false),[multi,setMulti]=useState(false),[elapsed,setElapsed]=useState(0),[running,setRunning]=useState(false),[admin,setAdmin]=useState(false);
 const lot=useMemo(()=>parkingAdapter.locateVehicle(),[]),jobs=useMemo(()=>scheduleCharging(multi?lot.vehicles:[lot.vehicles[0]],lot.modules),[multi,lot]),own=jobs.find(j=>j.id==='내 차량'),state=requested?chargingState(own,elapsed):parked?'차량 위치 확인 완료':'차량을 주차해 주세요',allComplete=requested&&jobs.every(j=>elapsed>=j.completeAt);
 useEffect(()=>{if(!running||allComplete)return;const timer=setInterval(()=>setElapsed(t=>t+(t<30?1:30)),500);return()=>clearInterval(timer);},[running,allComplete]);
 const modulePosition=(job)=>{if(elapsed<job.assignedAt)return job.path[0];if(elapsed>=job.startAt)return job.path.at(-1);let d=Math.max(0,elapsed-job.assignedAt)/Math.max(1,job.startAt-job.assignedAt-15)*job.travelMeters/parkingFixture.scaleMeters;for(let i=1;i<job.path.length;i++){const a=job.path[i-1],b=job.path[i],len=Math.hypot(a.x-b.x,a.y-b.y);if(d<=len){const f=len?d/len:1;return {x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f};}d-=len;}return job.path.at(-1);};
 const metrics=chargingMetrics(jobs);
 return <main className="contact-page"><div className="contact-title"><h1>{state}</h1></div><div className="parking-map"><svg viewBox="0 0 520 360" role="img" aria-label="실내 주차장과 충전 모듈 이동"><rect width="520" height="360" fill="#f8f9fa"/><path d="M30 180H490" stroke="#e3e6e8" strokeWidth="55"/>{[80,230].flatMap(y=>[80,180,280,380].map(x=><rect key={`${x}-${y}`} x={x} y={y} width="85" height="65" rx="8" fill="white" stroke="#bfc6cc"/>))}<text x="14" y="170" fontSize="17">출입구</text>{requested&&jobs.map(j=><polyline key={j.id} points={j.path.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#c0a900" strokeWidth="4" strokeDasharray="7 5"/>)}{parked&&(multi?lot.vehicles:[lot.vehicles[0]]).map(v=><g key={v.id}><rect x={v.x-25} y={v.y-18} width="50" height="36" rx="9" fill={v.id==='내 차량'?'#24292c':'#747c82'}/><text x={v.x} y={v.y+37} textAnchor="middle" fontSize="17">{v.id} {Math.round(v.battery+Math.max(0,Math.min(1,(elapsed-(jobs.find(j=>j.id===v.id)?.startAt||Infinity))/(jobs.find(j=>j.id===v.id)?.chargeSeconds||1)))*(v.targetBattery-v.battery))}%</text></g>)}{lot.modules.map(m=>{const assigned=jobs.filter(j=>j.moduleId===m.id&&j.assignedAt<=elapsed).at(-1),p=requested&&assigned?modulePosition(assigned):m;return <g key={m.id}><rect x={p.x-15} y={p.y-15} width="30" height="30" rx="7" fill="#fee500" stroke="#24292c"/><text x={p.x} y={p.y-23} textAnchor="middle" fontSize="16">{m.id}</text></g>;})}</svg></div><section className="contact-action">{!parked?<button className="arrival-primary" onClick={()=>setParked(true)}>이 위치에 주차하기</button>:!requested?<><p className="contact-reason">충전장치가 내 차량으로 찾아옵니다.</p><button className="arrival-primary" onClick={()=>{setRequested(true);setRunning(true);}}>자동충전 신청</button><button className="arrival-secondary" onClick={()=>setMulti(v=>!v)}>{multi?'내 차량만 신청':'여러 차량 동시 신청'}</button>{multi&&<p>다음 출차 예정 차량을 먼저 충전합니다.</p>}</>:<><h2>{own.moduleId} · {Math.round(own.energyKwh)} kWh</h2><progress aria-label="충전 진행률" value={Math.max(0,elapsed-own.startAt)} max={own.chargeSeconds}/>{multi&&<p className="contact-reason">다음 출차 예정 차량을 먼저 충전합니다.</p>}{allComplete?<><p>요청한 차량의 충전을 모두 완료했어요.</p><button className="arrival-primary" onClick={onBack}>이전 화면으로 돌아가기</button></>:<><button className="arrival-secondary" onClick={()=>setRunning(v=>!v)}>{running?'잠시 멈추기':'충전 계속하기'}</button><button className="arrival-secondary" onClick={()=>setElapsed(t=>Math.min(Math.max(...jobs.map(j=>j.completeAt)),t+120))}>2분 경과</button></>}<button className="arrival-secondary" onClick={()=>setAdmin(v=>!v)}>{admin?'관리자 결과 닫기':'관리자 결과 보기'}</button>{admin&&<section className="charging-admin"><h3>충전 운영 결과</h3><p>모듈 이동거리 {metrics.totalTravel}m</p><p>8시간 예상 처리량 {metrics.dailyThroughput}대</p>{jobs.map(j=><p key={j.id}>{j.id} · 출차 {j.departureMinutes}분 후 · 대기 {mins(j.waitSeconds)}분 · {chargingState(j,elapsed)}</p>)}</section>}</>}<button className="arrival-text-button" onClick={onBack}>이전 화면으로 돌아가기</button></section></main>;
}
