import {dispatchRobot} from './physical/robotDispatchEngine.js';
import {distance} from './places.js';
export const MODES=[{id:'taxi',name:'택시',speed:30},{id:'car',name:'자동차',speed:32},{id:'transit',name:'대중교통',speed:22},{id:'walk',name:'도보',speed:4.5},{id:'bike',name:'바이크',speed:15},{id:'wheelchair',name:'휠체어',speed:3.6}];
export const formatTime=ms=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(ms));
export function calculateArrivalTime(now,minutes){return now+Math.max(0,minutes)*60000;}
export function estimateEta(origin,destination,mode){const m=MODES.find(x=>x.id===mode)||MODES[0];return Math.max(1,Math.ceil(distance(origin,destination)*1.35/1000/m.speed*60+(mode==='transit'?7:mode==='taxi'?3:0)));}
export function inDealWindow(arrival,start,end){const [h,m]=formatTime(arrival).split(':').map(Number),n=h*60+m;const parse=s=>{const [a,b]=s.split(':').map(Number);return a*60+b;};const a=parse(start),b=parse(end);return a<=b?n>=a&&n<=b:n>=a||n<=b;}
export function calculateEtaFit(m,j){const active=m.discountPercent>0&&inDealWindow(j.estimatedArrivalTime,m.dealStart,m.dealEnd);const ready=m.prepMinutes+m.currentWaitMinutes<=j.etaMinutes;const readyDelay=Math.max(0,m.prepMinutes+m.currentWaitMinutes-j.etaMinutes);const close=m.closeTime&&!inDealWindow(calculateArrivalTime(j.estimatedArrivalTime,readyDelay),'00:00',m.closeTime);return {score:(active?60:0)+(ready?35:-Math.min(35,m.prepMinutes+m.currentWaitMinutes-j.etaMinutes))-(close?140:0),active,ready,close};}
export function calculateMerchantScore(m,j,preference='all'){const fit=calculateEtaFit(m,j),walk=Math.ceil(m.distance/75),wait=Math.max(0,Math.ceil(m.currentWaitMinutes+m.prepMinutes-j.etaMinutes-walk)),discount=fit.active?Math.round(m.price*m.discountPercent/100):0;const components={distanceScore:Math.max(0,15-m.distance/70),etaFitScore:fit.score,waitTimeScore:20-Math.min(65,wait*3),discountScore:fit.active?m.discountPercent*.7:0,congestionScore:({quiet:10,normal:3,busy:-12}[m.congestion]||0),preferenceScore:preference==='all'||m.category===preference?8:0};const unavailable=m.stockLevel<=0||m.pickupAvailable===false||m.capacity===0||fit.close;const reasons=[fit.ready?'도착 전 준비가 끝나요.':`도착 후 대기 약 ${wait}분을 예상해요.`,fit.active?`${m.dealEnd}까지 도착 시간대 할인이 있어요.`:'도착 시점에는 할인 시간대가 아니에요.',m.congestion==='quiet'?'현재 한산하고 도착 전에 준비할 수 있어요.':`목적지에서 ${Math.round(m.distance)}m예요.`];if(j.transportMode==='wheelchair')reasons.push('휠체어 경로 도착시간에 맞춰 준비 일정을 계산했어요.');if(j.transportMode==='bike'&&j.route?.type==='SAFE')reasons.push('우회 경로의 도착시간에도 받을 수 있는 상품이에요.');return {...m,...fit,waitAfterArrival:wait,discount,total:m.price-discount,components,reasons,unavailable,score:Object.values(components).reduce((a,b)=>a+b,0)-(unavailable?1000:0)};}
export function rankMerchants(merchants,journey,preference,physical){return merchants.map(m=>{const r=calculateMerchantScore(m,journey,preference);if(!physical)return r;const p=dispatchRobot({...physical,merchant:m,arrival:journey.estimatedArrivalTime});const physicalAgentFit=p.robotId?-Math.min(80,p.gap*12):-60;return {...r,score:r.score+physicalAgentFit,components:{...r.components,physicalAgentFit},reasons:[...r.reasons,p.gap===0?'전달 일정도 도착시간에 맞출 수 있어요.':'로봇 인계 가능 시각도 추천에 반영했어요.']};}).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));}
export function updateMerchantState(merchants,id,patch){return merchants.map(m=>m.id===id?{...m,...patch}:m);}
export function orderQuote(m,j,now){const ranked=calculateMerchantScore(m,j);if(ranked.unavailable)throw new Error('현재 주문할 수 없는 상품이에요.');return {merchant:ranked,original:m.price,discount:ranked.discount,total:ranked.total,arrival:j.estimatedArrivalTime,readyAt:Math.max(now+(m.prepMinutes+m.currentWaitMinutes)*60000,j.estimatedArrivalTime-3*60000)};}
