import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Car,Bus,Footprints,Bike,MapPin,LocateFixed,Search,Settings,X,Check,Clock,Gift,Navigation,Share2} from 'lucide-react';
import LiveMap from './LiveMap.jsx';
import {loadNavi} from './kakaoNavi.js';
import {searchArea,distanceLabel} from './places.js';
import {destinationFromURL,validDestination} from './journeyModel.js';
import {destinationShare,sendDestination,kakaoPlaceURL} from './destinationShare.js';
import {MODES,formatTime,calculateArrivalTime,estimateEta,rankMerchants,updateMerchantState,orderQuote} from './arrivalEngine.js';
import {demoMerchants,DEMO_DESTINATION,demoClock} from './demoMerchants.js';
import './arrival.css';
const money=n=>n.toLocaleString('ko-KR');
const icons={taxi:Car,car:Car,transit:Bus,walk:Footprints,bike:Bike};
const readOrders=()=>{try{const a=JSON.parse(localStorage.getItem('dangdo.arrival-orders'));return Array.isArray(a)?a.filter(o=>o?.isDemo&&typeof o.id==='string'&&Number.isSafeInteger(o.total)&&o.total>=0&&Number.isFinite(o.arrival)&&Number.isFinite(o.readyAt)&&validDestination(o.destination)&&validDestination(o.merchant)&&o.merchant?.isDemo).slice(0,30):[];}catch{return [];}};
function Sheet({title,onClose,children}){const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);return <dialog className="arrival-sheet" ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="sheet-head"><h2>{title}</h2><button aria-label="닫기" onClick={onClose}><X/></button></div>{children}</dialog>;}
export default function ArrivalApp(){
 const [stage,setStage]=useState('welcome'),[mode,setMode]=useState('taxi'),[origin,setOrigin]=useState(null),[destination,setDestination]=useState(()=>destinationFromURL(location.href)),[query,setQuery]=useState(''),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[locating,setLocating]=useState(false),[error,setError]=useState(''),[mapKey,setMapKey]=useState(import.meta.env.VITE_KAKAO_MAP_KEY||''),[gps,setGps]=useState(null),[sheet,setSheet]=useState(null),[clock,setClock]=useState(Date.now()),[demo,setDemo]=useState(false),[journey,setJourney]=useState(null),[merchants,setMerchants]=useState([]),[selected,setSelected]=useState(null),[notice,setNotice]=useState(''),[preference,setPreference]=useState('all'),[orders,setOrders]=useState(readOrders),[order,setOrder]=useState(null),[consent,setConsent]=useState(false),[sharePreview,setSharePreview]=useState(null),[demoAuto,setDemoAuto]=useState(false);
 const sequence=useRef(0),abort=useRef(),gpsSeq=useRef(0),payLock=useRef(false);
 useEffect(()=>{if(import.meta.env.VITE_KAKAO_MAP_KEY)loadNavi(import.meta.env.VITE_KAKAO_MAP_KEY).catch(()=>{});localStorage.removeItem('dangdo.kakao-key');return()=>{sequence.current++;gpsSeq.current++;abort.current?.abort();};},[]);
 useEffect(()=>{try{localStorage.setItem('dangdo.arrival-orders',JSON.stringify(orders));}catch{}},[orders]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{if(!demoAuto||stage!=='journey'||!journey?.etaMinutes)return;const t=setInterval(()=>advance(1),3000);return()=>clearInterval(t);},[demoAuto,stage,journey?.etaMinutes]);
 const ranked=useMemo(()=>journey?rankMerchants(merchants,journey,preference):[],[merchants,journey,preference]);
 const top=ranked[0];
 const setScreen=s=>{gpsSeq.current++;setLocating(false);sequence.current++;abort.current?.abort();setBusy(false);setStage(s);setError('');setResults(null);setQuery('');setConsent(false);window.scrollTo(0,0);};
 function choose(p){if(stage==='location'){setOrigin(p);if(destination){const now=demo?clock:Date.now(),minutes=demo?24:estimateEta(p,destination,mode);setClock(now);setJourney({origin:p,destination,transportMode:mode,etaMinutes:minutes,initialMinutes:minutes,estimatedArrivalTime:calculateArrivalTime(now,minutes)});setMerchants(demoMerchants(destination));}setScreen('destination');}else{setDestination(p);const now=demo?clock:Date.now(),minutes=demo?24:estimateEta(origin,p,mode);setClock(now);setJourney({origin,destination:p,transportMode:mode,etaMinutes:minutes,initialMinutes:minutes,estimatedArrivalTime:calculateArrivalTime(now,minutes)});setMerchants(demoMerchants(p));setSelected(null);setResults(null);setQuery('');setError('');}}
 async function search(e){e.preventDefault();if(!query.trim())return;const seq=++sequence.current;abort.current?.abort();abort.current=new AbortController();setBusy(true);setError('');try{const rows=await searchArea(query.trim(),mapKey,abort.current.signal);if(seq===sequence.current)setResults(rows);}catch(e){if(seq===sequence.current&&e.name!=='AbortError')setError('장소 검색 연결이 지연되고 있어요. 잠시 후 다시 검색해 주세요.');}finally{if(seq===sequence.current)setBusy(false);}}
 function locate(){if(!navigator.geolocation){setError('현재 위치를 사용할 수 없어요. 지역을 검색해 주세요.');return;}setLocating(true);setError('');const seq=++gpsSeq.current;navigator.geolocation.getCurrentPosition(p=>{if(seq!==gpsSeq.current)return;const point={name:'내 위치',lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};setGps(point);setLocating(false);choose(point);},e=>{if(seq!==gpsSeq.current)return;setLocating(false);setError(e.code===1?'위치 권한이 꺼져 있어요. 아래에서 출발 지역을 검색해 주세요.':'위치를 확인하지 못했어요. 출발 지역을 검색해 주세요.');},{enableHighAccuracy:true,timeout:12000,maximumAge:30000});}
 function startDemo(){sequence.current++;abort.current?.abort();gpsSeq.current++;setBusy(false);setLocating(false);setDemo(true);const now=demoClock(),p=DEMO_DESTINATION,o={name:'서울숲',lat:37.5445,lng:127.0374};setMode('taxi');setOrigin(o);setDestination(p);setGps(null);setClock(now);setJourney({origin:o,destination:p,transportMode:'taxi',etaMinutes:24,initialMinutes:24,estimatedArrivalTime:calculateArrivalTime(now,24)});setMerchants(demoMerchants(p));setSelected(null);setDemoAuto(false);setSheet(null);setPreference('all');setScreen('destination');}
 function advance(minutes){const elapsed=Math.min(minutes,journey?.etaMinutes||0);if(!elapsed)return;setClock(c=>c+elapsed*60000);setJourney(j=>j?{...j,etaMinutes:Math.max(0,j.etaMinutes-elapsed)}:j);setNotice('이동이 진행되어 도착 시점의 준비 상태를 다시 계산했어요.');}
 function delay(){setJourney(j=>({...j,etaMinutes:j.etaMinutes+19,estimatedArrivalTime:j.estimatedArrivalTime+19*60000}));setNotice('도착 시간이 변경되어 추천을 다시 계산했어요.');}
 function stateChange(){setMerchants(ms=>ms.map(m=>m.id==='demo-coffee'?{...m,currentWaitMinutes:m.currentWaitMinutes>10?0:22,congestion:m.currentWaitMinutes>10?'quiet':'busy'}:m.id==='demo-bowl'?{...m,currentWaitMinutes:4,congestion:'quiet'}:m));setNotice('매장 상태가 변경되어 추천을 업데이트했어요.');}
 function openMerchant(m){setSelected(m);setScreen('detail');}
 const current=selected&&journey?ranked.find(m=>m.id===selected.id):null;
 const quote=current&&journey?orderQuoteSafe(current,journey,clock):null;
 function confirmPayment(){if(payLock.current||!consent||!quote||!current)return;payLock.current=true;const newOrder={...quote,id:crypto.randomUUID(),isDemo:true,status:'confirmed',destination:journey.destination,code:String(Math.floor(1000+Math.random()*9000))};setOrders(prev=>[newOrder,...prev].slice(0,30));setOrder(newOrder);setScreen('complete');payLock.current=false;}
 async function share(place,withOrder=false){const template=destinationShare(location.origin+import.meta.env.BASE_URL,place);if(template.content)template.content.description=`나 ${formatTime(withOrder?order.arrival:journey.estimatedArrivalTime)}쯤 ${(withOrder?order.destination:journey.destination).name} 도착해!\n당도에서 ${place.name} 발견했어. 같이 갈래?${withOrder&&order.discount?'\nArrival Deal '+Math.round(order.discount/order.original*100)+'%':''}${place.isDemo?'\n예시 가맹점 · MVP 주문':''}`;try{const result=await sendDestination(template,window.Kakao,navigator);if(result==='copied'){setSharePreview({template,place});setSheet('share');setNotice('링크를 복사했어요. 카카오톡에 붙여 넣어 보내세요.');}}catch(e){if(e.name!=='AbortError'){setSharePreview({template,place});setSheet('share');setNotice('공유 연결을 사용할 수 없어 미리보기를 열었어요.');}}}
 const searchForm=<><form className="arrival-search" onSubmit={search}><Search size={20}/><input aria-label={stage==='location'?'출발 지역 검색':'목적지 검색'} placeholder={stage==='location'?'출발 지역이나 장소 검색':'어디로 갈까요?'} value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button disabled={busy||!query.trim()} aria-label="장소 검색">{busy?'…':<ArrowRight size={20}/>}</button></form>{error&&<p className="arrival-error" role="alert">{error}</p>}{results!==null&&<div className="search-candidates">{results.length?results.map((p,i)=><button key={i} onClick={()=>choose(p)}><MapPin size={18}/><span><b>{p.name}</b><small>{p.address}</small></span><ArrowRight size={18}/></button>):<p>검색 결과가 없어요. 지역명을 함께 입력해 주세요.</p>}</div>}</>;
 const navBack=()=>{if(stage==='mode'){setScreen('welcome');}else if(stage==='location')setScreen('mode');else if(stage==='destination')setScreen('location');else if(stage==='journey'){setDemoAuto(false);setScreen('destination');}else if(stage==='detail')setScreen('journey');else if(stage==='checkout')setScreen('detail');else setScreen('journey');};
 const routeMap=center=><div className="arrival-map"><LiveMap key={mapKey||'osm'} center={center} places={stage==='journey'?ranked:[]} selected={stage==='journey'?top:null} onSelect={p=>p.isDemo&&openMerchant(p)} onMove={()=>{}} gps={gps||origin} destination={destination} kakaoKey={mapKey} onError={()=>{setMapKey('');setNotice('카카오맵 연결이 지연되어 공개 지도로 전환했어요.');}}/><span className="map-provider">{mapKey?'카카오맵':'OpenStreetMap'}</span>{stage==='journey'&&<span className="map-demo-note">예시 가맹점 위치</span>}</div>;
 return <div className={`arrival-app ${stage==='welcome'?'welcome-app':''}`}>
 {stage==='welcome'?<main className="arrival-welcome"><div className="welcome-wordmark">kakao mobility</div><div className="arrival-logo"><Navigation size={56} fill="currentColor"/></div><h1>당도<span>DANGDO</span></h1><div className="welcome-copy"><h2>이동의 끝,<br/>좋은 순간의 시작</h2><p>도착할 때 가장 좋은 선택을 찾아드려요.</p></div><button className="arrival-primary" onClick={()=>setScreen('mode')}>시작하기<ArrowRight size={22}/></button><button className="welcome-settings" aria-label="설정" onClick={()=>setSheet('settings')}><Settings size={21}/></button></main>:<>
 <header className="arrival-header"><button aria-label="뒤로가기" onClick={navBack}><ArrowLeft/></button><button className="arrival-brand" onClick={()=>setSheet('settings')}>당도 <small>DANGDO</small></button><button aria-label="설정" onClick={()=>setSheet('settings')}><Settings size={21}/></button></header>
 {stage==='mode'&&<main className="arrival-page"><p className="step-label">01 이동</p><h1>어떻게 이동하나요?</h1><p className="page-sub">이동수단에 맞춰 도착 시간을 계산해요.</p><div className="mode-grid">{MODES.map(m=>{const Icon=icons[m.id];return <button key={m.id} aria-pressed={mode===m.id} className={mode===m.id?'chosen':''} onClick={()=>setMode(m.id)}><Icon size={30}/><b>{m.name}</b>{mode===m.id&&<Check size={17}/>}</button>;})}</div><button className="arrival-primary" onClick={()=>setScreen('location')}>출발 위치 설정<ArrowRight size={20}/></button></main>}
 {stage==='location'&&<main className="arrival-page"><p className="step-label">02 출발</p><h1>어디에서 출발하나요?</h1><p className="page-sub">현재 위치를 연결하거나 직접 찾아보세요.</p><button className="gps-card" disabled={locating} onClick={locate}><LocateFixed size={27}/><span><b>{locating?'위치를 확인하고 있어요':'현재 위치 사용'}</b><small>GPS로 출발 위치 연결</small></span><ArrowRight size={20}/></button><h2 className="region-heading">지역 검색</h2>{searchForm}<p className="privacy-note">위치는 버튼을 눌러 허용할 때만 사용해요.</p></main>}
 {stage==='destination'&&<main><div className="destination-heading"><p className="step-label">03 목적지</p><h1>어디로 갈까요?</h1>{searchForm}</div>{origin&&routeMap(destination||origin)}<section className="arrival-page route-summary">{destination&&journey?<><div className="route-line"><span>출발</span><b>{origin.name}</b></div><div className="route-line"><span>도착</span><b>{destination.name}</b></div><div className="eta-summary"><div><span>{MODES.find(m=>m.id===mode).name} 약 {journey.etaMinutes}분</span><strong>{formatTime(journey.estimatedArrivalTime)}</strong><b>도착 예정</b></div><Clock size={35}/></div><p className="data-note">{demo?'고정 시각을 사용하는 성수 이동 시나리오':'직선 거리와 이동수단으로 계산한 예상 시간 · 실시간 교통 미반영'}</p><button className="arrival-primary" onClick={()=>setScreen('journey')}>이 목적지로 출발<Navigation size={20}/></button></>:<p className="page-sub">지도에서 출발 위치를 확인하고 목적지를 검색해 주세요.</p>}</section></main>}
 {stage==='journey'&&journey&&<main><section className="journey-hero"><p>{journey.destination.name}{journey.etaMinutes?'으로 이동 중':'에 도착했어요'}</p><div className="journey-eta"><strong>{formatTime(journey.estimatedArrivalTime)}</strong><span>도착 예정</span></div><div className="journey-bottom"><b>{journey.etaMinutes?`도착까지 ${journey.etaMinutes}분`:'도착 후 바로 이용하세요'}</b><span>{MODES.find(m=>m.id===mode).name}</span></div><progress aria-label="이동 진행률" value={Math.max(0,journey.initialMinutes-journey.etaMinutes)} max={journey.initialMinutes}/><div className="progress-label"><span>출발</span><span>도착</span></div><small>{demo?'성수 이동 시나리오 · 가상 시각':'이동시간 추정 · GPS 실시간 추적 없음'}</small></section>{routeMap(journey.destination)}<section className="recommendation-section"><p className="step-label">ARRIVAL RECOMMENDATION</p><h2>도착하면 뭐 하지?</h2><p className="recommendation-time">{formatTime(journey.estimatedArrivalTime)}, {journey.destination.name}에서 가장 좋은 선택</p><div className="arrival-filters">{[['all','모두'],['카페','커피'],['음식점','식사']].map(([id,label])=><button key={id} aria-pressed={preference===id} className={preference===id?'chosen':''} onClick={()=>setPreference(id)}>{label}</button>)}</div><p className="data-note demo-label">Demo Merchant State · 예시 가맹점의 대기·재고·할인</p><div className="merchant-cards">{ranked.map((m,i)=><article className={`merchant-card ${i===0?'best-card':''}`} key={m.id} data-merchant={m.id}><div className="merchant-top"><span className="rank-pill">{i===0?'도착 맞춤 1위':`${i+1}위`}</span><small>{distanceLabel(m.distance)} · {m.category}</small></div><h3>{m.name}</h3><div className="merchant-state"><span>{({quiet:'한산함',normal:'보통',busy:'붐빔'})[m.congestion]}</span><span>현재 대기 {m.currentWaitMinutes}분</span><span>준비 {m.prepMinutes}분</span></div><p className={`eta-fit ${!m.ready?'waiting':''}`}>{m.unavailable?'현재 주문 불가':m.ready?'도착시간에 맞춰 준비 가능':`도착 후 대기 예상 ${m.waitAfterArrival}분`}</p><p className="deal-time">{m.active?`${m.dealStart}–${m.dealEnd} Arrival Deal ${m.discountPercent}%`:`${m.dealStart}–${m.dealEnd} 딜 · 도착 시점 적용 안 됨`}</p><div className="merchant-price">{m.discount>0&&<del>₩{money(m.price)}</del>}<strong>₩{money(m.total)}</strong><span>{m.product}</span></div>{m.reward&&<p className="reward-note"><Gift size={16}/>Arrival Reward · {m.reward.name}</p>}<details><summary>왜 추천했나요?</summary>{m.reasons.map(r=><p key={r}>{r}</p>)}</details><button className="arrival-primary" disabled={m.unavailable} onClick={()=>openMerchant(m)}>{m.unavailable?'재고 없음 또는 영업 종료':m.category==='카페'?'도착할 때 받기':'도착 맞춤 주문'}<ArrowRight size={18}/></button></article>)}</div><button className="arrival-secondary" onClick={()=>share(journey.destination)}><Share2 size={18}/>목적지 카카오톡 공유</button><button className="arrival-text-button" onClick={()=>setSheet('orders')}>주문 내역</button></section></main>}
 {(stage==='detail'||stage==='checkout')&&current&&quote&&<main className="arrival-page product-page"><p className="step-label">{stage==='checkout'?'KAKAO PAY':'ARRIVAL DEAL'}</p><h1>{current.name}</h1><p className="data-note">예시 가맹점 · Demo Merchant State</p><div className="product-illustration"><span>{current.category==='카페'?'COFFEE':'ARRIVAL MEAL'}</span><b>{current.product}</b></div><div className="fulfillment"><div><span>내 도착 예상</span><b>{formatTime(quote.arrival)}</b></div><div><span>준비 완료 예상</span><b>{formatTime(quote.readyAt)}</b></div></div><p className="eta-fit">{quote.readyAt<=quote.arrival?'도착 후 바로 픽업':'준비가 끝나면 픽업할 수 있어요'}</p>{current.reward&&<div className="arrival-reward"><Gift/><div><b>Arrival Reward</b><p>{current.reward.name}</p><small>{current.reward.terms}</small></div></div>}<div className="price-breakdown"><p><span>정가</span><b>{money(quote.original)}원</b></p><p><span>도착 할인{current.active?` ${current.discountPercent}%`:''}</span><b>−{money(quote.discount)}원</b></p><p className="total"><span>최종 결제</span><strong>{money(quote.total)}원</strong></p></div>{stage==='checkout'?<><div className="pay-method"><b>pay</b><span>카카오페이</span><Check size={19}/></div><label className="payment-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>MVP 결제 체험이며 실제 금액은 청구되지 않습니다. 매장에 주문이 전송되지 않습니다.</span></label><button className="arrival-primary" disabled={!consent} onClick={confirmPayment}>{money(quote.total)}원 결제</button></>:<><button className="arrival-primary" onClick={()=>setScreen('checkout')}>도착 맞춤 주문<ArrowRight size={20}/></button><a className="arrival-secondary" href={kakaoPlaceURL(journey.destination)} target="_blank" rel="noopener noreferrer">목적지 카카오맵에서 보기</a></>}</main>}
 {(stage==='detail'||stage==='checkout')&&!quote&&<main className="arrival-page"><h1>주문할 수 없는 상품이에요</h1><button className="arrival-primary" onClick={()=>setScreen('journey')}>추천 다시 보기</button></main>}
 {stage==='complete'&&order&&<main className="arrival-page complete-page"><div className="complete-check"><Check size={38}/></div><p className="step-label">ARRIVAL ORDER</p><h1>{order.status==='cancelled'?'주문을 취소했어요':<>도착할 때<br/>준비해둘게요</>}</h1><p className="data-note">MVP 주문 완료 · 실제 결제 및 매장 주문 없음</p><div className="order-ticket"><h2>{order.merchant.name}</h2><p>{order.merchant.product}</p><div className="fulfillment"><div><span>준비 완료 예상</span><b>{formatTime(order.readyAt)}</b></div><div><span>내 도착 예상</span><b>{formatTime(order.arrival)}</b></div></div><strong>{order.status==='cancelled'?'취소된 MVP 주문':order.readyAt<=order.arrival?'도착 후 바로 픽업':'준비 완료 후 픽업'}</strong><p>{money(order.total)}원 · 픽업번호 {order.code}</p>{order.merchant.reward&&<p className="reward-note"><Gift size={16}/>{order.merchant.reward.name}</p>}</div><div className="pickup-distance"><MapPin size={19}/>{order.destination.name}에서 예시 매장까지 {distanceLabel(order.merchant.distance)}</div><button className="arrival-primary" onClick={()=>share(order.merchant,true)}><Share2 size={19}/>카카오톡으로 공유</button><a className="arrival-secondary" href={kakaoPlaceURL(order.destination)} target="_blank" rel="noopener noreferrer">목적지 카카오맵에서 보기</a><button className="arrival-secondary" onClick={()=>setSheet('orders')}>주문 내역</button><button className="arrival-text-button" onClick={()=>setScreen('journey')}>이동 화면으로 돌아가기</button></main>}
 </>}
 {sheet==='settings'&&<Sheet title="설정" onClose={()=>setSheet(null)}><div className="sheet-body"><button className="settings-row" onClick={()=>setSheet('demo')}>Arrival Commerce Demo<ArrowRight size={20}/></button><button className="settings-row" onClick={()=>setSheet('orders')}>주문 내역<ArrowRight size={20}/></button><p className="data-note">지도와 장소 검색은 실제 API입니다. 예시 가맹점의 대기·재고·할인과 결제는 MVP 데이터입니다.</p><p className="data-note">당도는 카카오의 공식 앱이 아닌 독립 서비스입니다.</p></div></Sheet>}
 {sheet==='demo'&&<Sheet title="Arrival Commerce Demo" onClose={()=>setSheet(null)}><div className="sheet-body"><p className="page-sub">가상 시각과 예시 매장 상태로 도착 맞춤 추천을 확인해요.</p><button className="arrival-primary" onClick={startDemo}>성수 시나리오 시작 · 18:47</button>{journey&&<><button className="arrival-secondary" onClick={()=>{setDemo(true);delay();setSheet(null);setScreen('journey');}}>교통 체증 · ETA +19분</button><button className="arrival-secondary" onClick={()=>{setDemo(true);advance(10);setSheet(null);setScreen('journey');}}>이동 10분 진행</button><button className="arrival-secondary" onClick={()=>{stateChange();setSheet(null);setScreen('journey');}}>무브커피 대기 변화</button><label className="demo-toggle"><input type="checkbox" checked={demoAuto} onChange={e=>{setDemo(true);setDemoAuto(e.target.checked);}}/>자동 이동 · 3초마다 1분</label><h3>예시 매장 상태 편집</h3>{merchants.map(m=><div className="state-editor" key={m.id}><b>{m.name}</b><label>대기시간<input aria-label={`${m.name} 대기시간`} type="number" min="0" max="120" value={m.currentWaitMinutes} onChange={e=>{setMerchants(ms=>updateMerchantState(ms,m.id,{currentWaitMinutes:Math.max(0,Math.min(120,Number(e.target.value)||0))}));setNotice('매장 상태가 변경되어 추천을 업데이트했어요.');}}/></label><label>혼잡도<select aria-label={`${m.name} 혼잡도`} value={m.congestion} onChange={e=>setMerchants(ms=>updateMerchantState(ms,m.id,{congestion:e.target.value}))}><option value="quiet">한산함</option><option value="normal">보통</option><option value="busy">붐빔</option></select></label><label>재고<input aria-label={`${m.name} 재고`} type="number" min="0" max="99" value={m.stockLevel} onChange={e=>setMerchants(ms=>updateMerchantState(ms,m.id,{stockLevel:Math.max(0,Math.min(99,Number(e.target.value)||0))}))}/></label><label>할인율<input aria-label={`${m.name} 할인율`} type="number" min="0" max="90" value={m.discountPercent} onChange={e=>setMerchants(ms=>updateMerchantState(ms,m.id,{discountPercent:Math.max(0,Math.min(90,Number(e.target.value)||0))}))}/></label></div>)}</>}</div></Sheet>}
 {sheet==='orders'&&<Sheet title="주문 내역" onClose={()=>setSheet(null)}><div className="sheet-body">{orders.length?orders.map(o=><article className="history-order" key={o.id}><small>MVP 주문 · {o.status==='cancelled'?'취소됨':'준비 예정'}</small><h3>{o.merchant.name}</h3><p>{o.merchant.product} · {money(o.total)}원</p><p>{formatTime(o.readyAt)} 준비 / {formatTime(o.arrival)} 도착</p>{o.status!=='cancelled'&&<><button className="arrival-secondary" onClick={()=>{setOrder(o);setSheet(null);setScreen('complete');}}>주문 보기</button><button className="arrival-text-button" onClick={()=>{setOrders(os=>os.map(a=>a.id===o.id?{...a,status:'cancelled'}:a));if(order?.id===o.id)setOrder({...o,status:'cancelled'});setNotice('MVP 주문을 취소했어요.');}}>주문 취소</button></>}</article>):<p>아직 주문 내역이 없어요.</p>}</div></Sheet>}
 {sheet==='share'&&sharePreview&&<Sheet title="카카오톡 공유 미리보기" onClose={()=>setSheet(null)}><div className="sheet-body"><h3>{sharePreview.place.name}</h3><p className="share-copy">{sharePreview.template.content?.description}</p><a className="arrival-primary" href={sharePreview.template.content?.link.webUrl} target="_blank" rel="noopener noreferrer">지도 열기</a><button className="arrival-secondary" onClick={async()=>{try{await navigator.clipboard.writeText([sharePreview.template.content?.description,sharePreview.template.content?.link.webUrl].join('\n'));setNotice('공유 내용을 복사했어요.');}catch{setNotice('복사 권한이 없어요. 아래 링크를 길게 눌러 복사해 주세요.');}}}>공유 내용 복사</button><a className="share-link" href={sharePreview.template.content?.link.webUrl}>{sharePreview.template.content?.link.webUrl}</a></div></Sheet>}
 {notice&&<div className="arrival-toast" role="status">{notice}</div>}
 </div>;
}
function orderQuoteSafe(m,j,clock){try{return orderQuote(m,j,clock);}catch{return null;}}
