let context,clip,settings=null;
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open('dangdo-audio',1);req.onupgradeneeded=()=>req.result.createObjectStore('clips');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function persist(value){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('clips','readwrite');if(value)tx.objectStore('clips').put(value,'arrival');else tx.objectStore('clips').delete('arrival');tx.oncomplete=()=>{database.close();resolve();};tx.onerror=()=>{database.close();reject(tx.error);};});}
export function unlockChime(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return false;context ||= new Audio();if(context.state==='suspended')context.resume().catch(()=>{});return true;}catch{return false;}}
async function restoreDefault(){try{if(!unlockChime())return null;const response=await fetch(import.meta.env.BASE_URL+'audio/kakao-arrival.wav');if(!response.ok)return null;clip=await context.decodeAudioData(await response.arrayBuffer());settings={name:'카카오 도착 알림음',start:0,duration:1};return settings;}catch{return null;}}
export async function restoreChime(){try{const database=await db();const value=await new Promise((resolve,reject)=>{const req=database.transaction('clips').objectStore('clips').get('arrival');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});database.close();if(value&&unlockChime()){clip=await context.decodeAudioData(value.data.slice(0));settings=value;return {name:value.name,start:value.start,duration:value.duration};}}catch{}return restoreDefault();}
export async function configureChime(file,start,duration){if(!file||file.size>30*1024*1024)throw new Error('30MB 이하의 음원 또는 영상 파일을 선택해 주세요.');if(!Number.isFinite(start)||start<0||!Number.isFinite(duration)||duration<.2||duration>10)throw new Error('시작 시간은 0초 이상, 길이는 0.2~10초로 설정해 주세요.');if(!unlockChime())throw new Error('이 브라우저에서 소리를 재생할 수 없어요.');const data=await file.arrayBuffer();let decoded;try{decoded=await context.decodeAudioData(data.slice(0));}catch{throw new Error('읽을 수 없는 파일이에요. MP3나 WAV 파일을 사용해 주세요.');}if(start>=decoded.duration)throw new Error('시작 시간이 파일 길이보다 길어요.');const value={name:file.name,data,start,duration:Math.min(duration,decoded.duration-start)};await persist(value);clip=decoded;settings=value;return {name:value.name,start:value.start,duration:value.duration};}
export async function removeChime(){await persist(null);clip=null;settings=null;}
export function playChime(){if(!clip||!settings||!unlockChime())return false;const source=context.createBufferSource(),gain=context.createGain();source.buffer=clip;gain.gain.value=.4;source.connect(gain);gain.connect(context.destination);source.start(context.currentTime+.03,settings.start,settings.duration);source.onended=()=>{source.disconnect();gain.disconnect();};return true;}
