const PREFIX='dangdo.account.';
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=a=>{const data=new Uint8Array(a);let str='';for(let i=0;i<data.length;i+=8192)str+=String.fromCharCode(...data.subarray(i,i+8192));return btoa(str);};
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export function accountId(value){const id=String(value||'').trim().toLowerCase();if(!/^[a-z0-9_]{4,32}$/.test(id))throw new Error('아이디는 영문, 숫자, 밑줄로 4~32자를 입력하세요.');return id;}
async function keyFor(password,salt){if(typeof password!=='string'||password.length<10||password.length>128)throw new Error('비밀번호는 10~128자를 입력하세요.');const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:310000},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function sealProfile(id,password,profile={}){id=accountId(id);const nickname=String(profile.nickname||'').trim().slice(0,80)||'당도 사용자',picture=profile.picture||null;if(picture&&(!/^data:image\/(jpeg|png|webp);base64,/.test(picture)||picture.length>300000))throw new Error('프로필 사진 크기를 줄여 주세요.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(password,salt);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(id)},key,enc.encode(JSON.stringify({id,nickname,picture,kind:'device'})));return {version:1,salt:b64(salt),iv:b64(iv),cipher:b64(cipher)};}
export async function openProfile(id,password,record){id=accountId(id);try{if(record?.version!==1||typeof record.cipher!=='string'||record.cipher.length>500000)throw new Error();const salt=bytes(record.salt),iv=bytes(record.iv);if(salt.length!==16||iv.length!==12)throw new Error();const key=await keyFor(password,salt),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode(id)},key,bytes(record.cipher));const p=JSON.parse(dec.decode(raw));if(p.id!==id||typeof p.nickname!=='string')throw new Error();return p;}catch{throw new Error('아이디 또는 비밀번호를 확인해 주세요.');}}
export async function registerDevice(id,password,profile){id=accountId(id);if(localStorage.getItem(PREFIX+id))throw new Error('이 기기에 이미 등록된 아이디예요.');const record=await sealProfile(id,password,profile);localStorage.setItem(PREFIX+id,JSON.stringify(record));return openProfile(id,password,record);}
export async function loginDevice(id,password){id=accountId(id);let record;try{record=JSON.parse(localStorage.getItem(PREFIX+id));}catch{}return openProfile(id,password,record);}
export function rememberDevice(user){sessionStorage.setItem('dangdo.device-session',JSON.stringify({user,expires:Date.now()+8*3600000}));}
export function readDevice(){try{const r=JSON.parse(sessionStorage.getItem('dangdo.device-session'));return r?.expires>Date.now()&&r.user?.kind==='device'?r.user:null;}catch{return null;}}
export function forgetDevice(){sessionStorage.removeItem('dangdo.device-session');}
