import React,{useState} from 'react';
import {UserRound,ImagePlus,LoaderCircle,LogOut} from 'lucide-react';
import {registerDevice,loginDevice,rememberDevice} from './deviceAccount.js';
export default function DeviceAccount({user,onUser,onLogout,Dialog,onClose,kakaoReady,onKakao}){
 const [signup,setSignup]=useState(false),[id,setId]=useState(''),[password,setPassword]=useState(''),[nickname,setNickname]=useState(''),[picture,setPicture]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const next=signup?await registerDevice(id,password,{nickname,picture}):await loginDevice(id,password);rememberDevice(next);setPassword('');onUser(next);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function photo(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5000000){setError('JPG, PNG, WebP 사진을 5MB 이내로 선택하세요.');return;}try{const bmp=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=canvas.height=160;const c=canvas.getContext('2d'),side=Math.min(bmp.width,bmp.height);c.drawImage(bmp,(bmp.width-side)/2,(bmp.height-side)/2,side,side,0,0,160,160);bmp.close();setPicture(canvas.toDataURL('image/jpeg',.8));setError('');}catch{setError('사진을 불러오지 못했어요.');}}
 if(user)return <Dialog title="내 프로필" onClose={onClose}><div className="dialog-body device-account"><div className="device-profile">{user.picture?<img src={user.picture} alt="내 프로필"/>:<UserRound size={42}/>}<h3>{user.nickname}</h3></div><p>{user.kind==='device'?'이 브라우저에 등록한 당도 계정입니다.':'카카오 계정으로 연결했어요.'}</p><button className="dd-primary" onClick={onLogout}><LogOut size={18}/>로그아웃</button></div></Dialog>;
 return <Dialog title={signup?'당도 계정 만들기':'당도 로그인'} onClose={onClose}><form className="dialog-body device-account" onSubmit={submit}><p className="device-note">이 기기의 브라우저에서 사용하는 계정이에요. 다른 기기와 동기화되거나 카카오 계정에 연결되지는 않아요.</p><label>아이디<input required autoComplete="username" value={id} onChange={e=>setId(e.target.value)} minLength={4} maxLength={32} placeholder="영문, 숫자, 밑줄"/></label><label>비밀번호<input required type="password" autoComplete={signup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={10} maxLength={128} placeholder="10자 이상"/></label>{signup&&<><label>닉네임 <small>선택</small><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={80} placeholder="당도 사용자"/></label><label className="device-photo">{picture?<img src={picture} alt="선택한 프로필 사진"/>:<ImagePlus size={25}/>}<span>프로필 사진 선택</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>photo(e.target.files?.[0])}/></label><p className="muted-text">닉네임과 사진 없이도 가입할 수 있어요.</p></>}{error&&<p role="alert" className="inline-error">{error}</p>}<button className="dd-primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={20}/>:signup?'계정 만들기':'로그인'}</button><button type="button" className="dd-secondary" disabled={busy} onClick={()=>{setSignup(v=>!v);setError('');setPassword('');}}>{signup?'기존 계정으로 로그인':'새 계정 만들기'}</button>{kakaoReady&&<button type="button" className="dd-secondary" onClick={onKakao}>카카오톡으로 로그인</button>}</form></Dialog>;
}
