import React,{useEffect,useRef,useState} from 'react';
import {MapPin,Navigation,Gift,Volume2,VolumeX,Check,ChevronRight,Copy,Link,LoaderCircle,Coffee,Utensils,ShoppingBag,ReceiptText,LocateFixed,Pause,Play,Minus,Plus,ArrowLeft,Upload} from 'lucide-react';
import {distanceLabel,routeURL,searchArea} from './places.js';
import {APPROACH_METERS,validDestination,parseSharedDestination,proximity} from './journeyModel.js';
import {loadNavi,navigateNavi} from './kakaoNavi.js';
import {unlockChime,playChime,restoreChime,configureChime,removeChime} from './chime.js';
const money=n=>n.toLocaleString('ko-KR');
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
function loadTrip(){const t=read('dangdo.journey',null);return t&&typeof t.id==='string'&&validDestination(t.destination)?t:null;}
export default function Journey({area,gps,kakaoKey,onDestination,onGPS,onActiveDestination,onConnect,Dialog}){
 const [trip,setTrip]=useState(loadTrip),[tracking,setTracking]=useState(false),[geoMessage,setGeoMessage]=useState(''),[modal,setModal]=useState(null),[audioOn,setAudioOn]=useState(()=>read('dangdo.sound-on',true)),[audio,setAudio]=useState(null),[soundFile,setSoundFile]=useState(null),[clipStart,setClipStart]=useState(0),[clipDuration,setClipDuration]=useState(1),[soundBusy,setSoundBusy]=useState(false),[shared,setShared]=useState(''),[sharedResults,setSharedResults]=useState([]),[sharedBusy,setSharedBusy]=useState(false),[message,setMessage]=useState(''),[navReady,setNavReady]=useState(false),[navError,setNavError]=useState('');
 const latest=useRef(),inflight=useRef(false),requestId=useRef(null),sharedAbort=useRef(),notified=useRef(new Set());latest.current={trip,audioOn,onDestination,onGPS,onActiveDestination};
 const destination=trip?.destination||area,approach=proximity(destination,gps),changed=trip&&(area.lat!==trip.destination.lat||area.lng!==trip.destination.lng||area.name!==trip.destination.name);
 useEffect(()=>{if(trip){onDestination(trip.destination);onActiveDestination(trip.destination);}restoreChime().then(setAudio);return()=>sharedAbort.current?.abort();},[]);
 useEffect(()=>{save('dangdo.journey',trip);onActiveDestination(trip?.destination||null);},[trip]);
 useEffect(()=>{save('dangdo.sound-on',audioOn);},[audioOn]);
 useEffect(()=>{let dead=false;setNavReady(false);setNavError('');if(kakaoKey)loadNavi(kakaoKey).then(()=>{if(!dead)setNavReady(true);}).catch(e=>{if(!dead)setNavError(e.message);});return()=>{dead=true;};},[kakaoKey]);
 useEffect(()=>{
  if(!tracking||!trip)return;if(!navigator.geolocation){setTracking(false);setGeoMessage('이 브라우저는 위치 기능을 지원하지 않아요.');return;}
  let watch=null,dead=false;
  const success=p=>{if(dead)return;const point={name:'내 위치',lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};latest.current.onGPS(point);const current=latest.current.trip;if(!current)return;const result=proximity(current.destination,point);setGeoMessage(result.reliable?'':'위치 오차가 커서 접근 알림을 기다리고 있어요.');if(result.near&&!current.notified&&!notified.current.has(current.id)){notified.current.add(current.id);setTrip(t=>t?.id===current.id?{...t,notified:true}:t);if(!document.hidden){setModal('arrival');if(latest.current.audioOn)playChime();}}};
  const failure=e=>{if(dead)return;setGeoMessage(e.code===1?'위치 권한을 허용하면 도착지 접근을 확인할 수 있어요.':'위치를 확인하지 못했어요. 잠시 후 다시 확인해 주세요.');if(e.code===1)setTracking(false);};
  const start=()=>{if(watch!==null)navigator.geolocation.clearWatch(watch);if(document.hidden){watch=null;return;}watch=navigator.geolocation.watchPosition(success,failure,{enableHighAccuracy:true,timeout:15000,maximumAge:5000});};
  start();document.addEventListener('visibilitychange',start);return()=>{dead=true;if(watch!==null)navigator.geolocation.clearWatch(watch);document.removeEventListener('visibilitychange',start);};
 },[tracking,trip?.id]);
 function begin(provider){if(provider==='navi'&&!navReady){onConnect();setModal(null);return;}unlockChime();let next=trip;if(!trip||changed){next={id:crypto.randomUUID(),destination:{name:area.name,lat:area.lat,lng:area.lng},startedAt:new Date().toISOString(),notified:false};setTrip(next);}onDestination(next.destination);setTracking(true);setModal(null);setGeoMessage('');if(provider==='navi')try{navigateNavi(next.destination);}catch(e){setMessage(e.message);} }
 async function importShared(e){e.preventDefault();setMessage('');setSharedResults([]);try{const parsed=parseSharedDestination(shared);if(parsed.destination){onDestination(parsed.destination);setModal(null);return;}setSharedBusy(true);sharedAbort.current?.abort();sharedAbort.current=new AbortController();const results=await searchArea(parsed.query,kakaoKey,sharedAbort.current.signal);setSharedResults(results);if(!results.length)setMessage('장소를 찾지 못했어요. 장소 이름이나 주소를 다시 입력해 주세요.');}catch(e){if(e.name!=='AbortError')setMessage(e.message);}finally{setSharedBusy(false);}}
 async function copyDestination(){const url=new URL(location.origin+import.meta.env.BASE_URL);url.searchParams.set('destName',destination.name);url.searchParams.set('destLat',destination.lat);url.searchParams.set('destLng',destination.lng);try{await navigator.clipboard.writeText(url.href);setMessage('목적지 링크를 복사했어요.');}catch{setMessage(url.href);}}
 async function setSound(){setMessage('');setSoundBusy(true);try{const value=await configureChime(soundFile,Number(clipStart),Number(clipDuration));setAudio(value);setAudioOn(true);playChime();setMessage('선택한 구간을 도착 알림으로 저장했어요.');}catch(e){setMessage(e.message);}finally{setSoundBusy(false);}}
 return <div className="journey-module">
  <div className="journey-destination"><div className="destination-marker"><MapPin size={22}/></div><div><span>{trip?'이동 중인 목적지':'선택한 목적지'}</span><strong>{destination.name}</strong></div><button className="journey-audio" onClick={()=>{setMessage('');setModal('sound');}} aria-label="도착 알림음 설정">{audioOn&&audio?<Volume2 size={21}/>:<VolumeX size={21}/>}</button></div>
  {trip&&<div className="journey-status"><span className={tracking?'tracking-dot':''}/>{approach.meters!==null?`목적지까지 직선 ${distanceLabel(approach.meters)}`:'GPS를 켜면 목적지 접근을 확인해요'}<button onClick={()=>{unlockChime();setTracking(v=>!v);}}>{tracking?<><Pause size={14}/>중지</>:<><LocateFixed size={14}/>GPS 켜기</>}</button></div>}
  {geoMessage&&<p className="journey-help" role="status">{geoMessage}</p>}
  {changed&&<button className="destination-change" onClick={()=>setModal('launch')}>{area.name}(으)로 목적지 변경<ChevronRight size={16}/></button>}
  <button className="dd-primary journey-start" onClick={()=>{setMessage('');setModal('launch');}}><Navigation size={19}/>{trip?'길 안내 다시 열기':'이 목적지로 출발'}</button>
  <div className="journey-links"><button onClick={()=>{setMessage('');setModal('import');}}><Link size={16}/>카카오 공유 가져오기</button></div>
  {trip&&<div className="trip-actions"><button onClick={()=>{setTracking(false);setTrip(null);setGeoMessage('');}}>이동 종료</button></div>}
  {!kakaoKey&&<button className="kakao-connect-inline" onClick={onConnect}>카카오맵 내비 연결하기<ChevronRight size={17}/></button>}
  {modal==='launch'&&<Dialog title={changed?'목적지 변경':'목적지로 출발'} onClose={()=>{setModal(null);setMessage('');}}><div className="dialog-body"><div className="launch-destination"><MapPin size={25}/><h3>{changed?area.name:destination.name}</h3></div><p>목적지까지 길 안내를 열고 주변 식당을 확인하세요.</p><a className="dd-primary" href={routeURL(changed?area:destination,gps,'car')} target="_blank" rel="noopener noreferrer" onClick={()=>begin('map')}><Navigation size={19}/>카카오맵으로 출발</a><button className="dd-secondary" onClick={()=>begin('navi')} disabled={!!kakaoKey&&!navReady}>{kakaoKey?(navReady?'카카오내비로 출발':'카카오내비 연결 중'):'카카오내비 연결 설정'}</button><button className="dd-secondary" onClick={()=>begin('here')}>당도에서 먼저 둘러보기</button>{navError&&<p role="alert">{navError}</p>}<p className="journey-help">출발하면 GPS를 요청해요. 당도 화면이 열려 있을 때 목적지 800m 이내 접근을 확인하며, 지도 앱에서 돌아오면 다시 확인해요.</p><p className="journey-help">위치 이력은 저장하지 않아요. 현재 지도 위치와 목적지는 장소 검색에 사용돼요.</p>{message&&<p role="status">{message}</p>}</div></Dialog>}
  {modal==='arrival'&&<Dialog title="목적지 근처에 도착했어요" onClose={()=>setModal(null)}><div className="dialog-body"><div className="arrival-symbol"><MapPin size={36}/></div><h3>{destination.name} 주변을 확인하세요</h3><p>GPS로 목적지 800m 이내 접근을 확인했어요.</p><button className="dd-primary" onClick={()=>{setModal(null);onDestination(destination);}}>주변 식당 보기</button></div></Dialog>}
  {modal==='import'&&<Dialog title="카카오 공유 가져오기" onClose={()=>{sharedAbort.current?.abort();setModal(null);}}><form className="dialog-body" onSubmit={importShared}><p>카카오맵에서 장소를 선택하고 공유 내용을 복사한 뒤 여기에 붙여넣으세요.</p><textarea value={shared} onChange={e=>setShared(e.target.value)} maxLength={3000} aria-label="카카오 공유 내용" placeholder={'[카카오맵] 성수역\n서울 성동구 아차산로 100\n공유 링크'}/><button className="dd-primary" type="submit" disabled={sharedBusy||!shared.trim()}>{sharedBusy?<LoaderCircle className="spin" size={19}/>:<Link size={18}/>}목적지 가져오기</button>{sharedResults.map((p,i)=><button type="button" className="area-result" key={i} onClick={()=>{onDestination(p);setModal(null);}}><MapPin size={19}/><span><strong>{p.name}</strong><span>{p.address}</span></span></button>)}{message&&<p className="inline-error" role="status">{message}</p>}<p className="journey-help">좌표가 없는 짧은 링크는 장소 이름 주소가 함께 필요해요. 카카오 앱의 목적지를 자동으로 읽지는 않아요.</p><button type="button" className="settings-link" onClick={copyDestination}><Copy size={17}/>현재 목적지의 당도 링크 복사</button></form></Dialog>}
  {modal==='sound'&&<Dialog title="도착 알림음" onClose={()=>setModal(null)}><div className="dialog-body"><p>제공한 카카오 음원의 처음 1초를 도착 알림으로 사용해요.</p>{audio&&<><p className="sound-file">{audio.name}   {audio.start}초부터 {audio.duration.toFixed(1)}초</p><div className="sound-buttons"><button className="dd-secondary" onClick={()=>{unlockChime();playChime();}}><Play size={17}/>미리 듣기</button><button className="dd-secondary" onClick={()=>{unlockChime();setAudioOn(v=>!v);}}>{audioOn?<Volume2 size={18}/>:<VolumeX size={18}/>}소리 {audioOn?'켜짐':'꺼짐'}</button></div></>}<label className="audio-upload"><Upload size={22}/><span>{soundFile?soundFile.name:'음원 영상 파일 선택'}</span><input type="file" accept="audio/*,video/mp4,video/webm" onChange={e=>setSoundFile(e.target.files?.[0]||null)}/></label><div className="clip-fields"><label>시작(초)<input type="number" min="0" step="0.1" value={clipStart} onChange={e=>setClipStart(e.target.value)}/></label><label>길이(초)<input type="number" min="0.2" max="10" step="0.1" value={clipDuration} onChange={e=>setClipDuration(e.target.value)}/></label></div><button className="dd-primary" disabled={!soundFile||soundBusy} onClick={setSound}>{soundBusy?'음원 준비 중':'이 구간을 알림음으로 저장'}</button>{audio&&<button className="settings-link" onClick={async()=>{try{await removeChime();setAudio(await restoreChime());setAudioOn(true);}catch{setMessage('음원을 지우지 못했어요. 다시 시도해 주세요.');}}}>기본 알림음으로 복원</button>}{message&&<p role="status">{message}</p>}<p className="journey-help">음원은 이 브라우저에만 저장해요. 기본 알림음은 제공한 음원의 첫 1초예요. 다른 앱을 사용하는 동안에는 알림음이 보장되지 않아요.</p></div></Dialog>}
 </div>;
}
