import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Search,Navigation,LocateFixed,SlidersHorizontal,Sparkles,Bookmark,Compass,X,ChevronRight,ArrowLeft,Utensils,Coffee,LoaderCircle,Phone,Check,Map as MapIcon,Car,Footprints,Bus,Plus,ExternalLink} from 'lucide-react';
import Demo from './Demo.jsx';
import LiveMap from './LiveMap.jsx';
import Journey from './Journey.jsx';
import {destinationFromURL} from './journeyModel.js';
import './journey.css';
import {AREAS,nearbyOSM,nearbyKakao,loadKakao,searchArea,distanceLabel,routeURL,placeText,rankPlaces} from './places.js';
import './discover.css';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
const Icon=({place,...props})=>place.kind==='카페'?<Coffee {...props}/>:<Utensils {...props}/>;
function Dialog({title,onClose,children}){const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="dd-dialog" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-label={title}><div className="dialog-heading"><h2>{title}</h2><button className="round-button" onClick={onClose} aria-label="닫기"><X/></button></div>{children}</dialog>}
function App(){
 const [area,setArea]=useState(()=>destinationFromURL(location.href)||AREAS[0]),[center,setCenter]=useState(()=>destinationFromURL(location.href)||AREAS[0]),[moved,setMoved]=useState(null),[gps,setGps]=useState(null),[locating,setLocating]=useState(false),[places,setPlaces]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('전체'),[selected,setSelected]=useState(null),[radius,setRadius]=useState(1500),[refresh,setRefresh]=useState(0),[query,setQuery]=useState(''),[areaResults,setAreaResults]=useState(null),[searchBusy,setSearchBusy]=useState(false),[searchError,setSearchError]=useState(''),[view,setView]=useState('explore'),[saved,setSaved]=useState(()=>read('dangdo.saved',[])),[dialog,setDialog]=useState(null),[key,setKey]=useState(()=>read('dangdo.kakao-key','')||import.meta.env.VITE_KAKAO_MAP_KEY||''),[keyDraft,setKeyDraft]=useState(key),[aiQuery,setAiQuery]=useState(''),[aiState,setAiState]=useState('idle'),[aiStatus,setAiStatus]=useState(''),[aiResults,setAiResults]=useState(null),[aiError,setAiError]=useState(''),[travel,setTravel]=useState('walk'),[demo,setDemo]=useState(false);
 const [activeDestination,setActiveDestination]=useState(null);
 const searchAbort=useRef(),searchSequence=useRef(0),worker=useRef(),aiId=useRef(0),aiTimeout=useRef(),gpsSequence=useRef(0);
 function stopAI(){aiId.current++;clearTimeout(aiTimeout.current);worker.current?.terminate();worker.current=null;setAiState('idle');setAiStatus('');}
 useEffect(()=>{write('dangdo.saved',saved);},[saved]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>()=>{searchAbort.current?.abort();worker.current?.terminate();clearTimeout(aiTimeout.current);gpsSequence.current++;},[]);
 useEffect(()=>{const controller=new AbortController();let dead=false;setBusy(true);setError('');setPlaces([]);setSelected(null);setAiResults(null);setAiError('');stopAI();
  (async()=>{try{let rows;if(key){try{rows=await nearbyKakao(await loadKakao(key),center,radius);}catch(e){if(dead)return;setNotice('카카오 연결을 확인해 주세요. 공개 지도로 전환했어요.');setKey('');write('dangdo.kakao-key','');return;}}else rows=await nearbyOSM(center,radius,controller.signal);if(!dead)setPlaces(rows);}catch(e){if(!dead)setError('주변 식당을 불러오지 못했어요. 잠시 후 다시 검색해 주세요.');}finally{if(!dead)setBusy(false);}})();return()=>{dead=true;controller.abort();};
 },[center,radius,refresh,key]);
 const shown=useMemo(()=>{const source=view==='saved'?saved:(aiResults||places);return source.filter(p=>filter==='전체'||(filter==='카페'?p.kind==='카페':p.kind!=='카페'));},[places,aiResults,saved,filter,view]);
 function chooseArea(p){searchSequence.current++;searchAbort.current?.abort();setSearchBusy(false);setArea(p);setCenter(p);setMoved(null);setAreaResults(null);setQuery('');setView('explore');setSelected(null);}
 async function findArea(e){e.preventDefault();if(!query.trim()||searchBusy)return;const seq=++searchSequence.current;searchAbort.current?.abort();searchAbort.current=new AbortController();setSearchBusy(true);setSearchError('');try{const results=await searchArea(query.trim(),key,searchAbort.current.signal);if(seq===searchSequence.current)setAreaResults(results);}catch(e){if(seq===searchSequence.current&&e.name!=='AbortError')setSearchError('장소 검색에 실패했어요. 다시 시도해 주세요.');}finally{if(seq===searchSequence.current)setSearchBusy(false);}}
 function locate(){if(!navigator.geolocation){setNotice('이 브라우저는 위치 기능을 지원하지 않아요. 목적지를 검색해 주세요.');return;}const seq=++gpsSequence.current;setLocating(true);navigator.geolocation.getCurrentPosition(p=>{if(seq!==gpsSequence.current)return;const point={name:'내 위치',lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};setGps(point);if(!activeDestination)chooseArea(point);setLocating(false);if(p.coords.accuracy>200)setNotice('위치 오차가 커요. 지도에서 검색할 위치를 조정할 수 있어요.');},e=>{if(seq!==gpsSequence.current)return;setLocating(false);setNotice(e.code===1?'위치 권한이 꺼져 있어요. 브라우저 설정에서 허용하거나 목적지를 검색해 주세요.':e.code===3?'위치를 확인하는 데 시간이 걸려요. 다시 시도해 주세요.':'위치를 확인하지 못했어요. 목적지를 검색해 주세요.');},{enableHighAccuracy:true,timeout:15000,maximumAge:30000});}
 function toggleSave(p){setSaved(prev=>prev.some(x=>x.id===p.id)?prev.filter(x=>x.id!==p.id):[p,...prev].slice(0,100));}
 function startAI(){if(!aiQuery.trim()||!places.length||aiState==='working')return;const candidates=places.filter(p=>filter==='전체'||(filter==='카페'?p.kind==='카페':p.kind!=='카페')).slice(0,30);if(!candidates.length){setAiError('이 종류의 식당이 없어요. 다른 종류를 선택해 주세요.');return;}setAiError('');setAiResults(null);setAiState('working');setAiStatus('AI 모델 준비 중');const id=++aiId.current;
  try{worker.current ||= new Worker(new URL('./recommend.worker.js',import.meta.url),{type:'module'});worker.current.onmessage=({data})=>{if(data.id!==aiId.current)return;if(data.type==='progress')setAiStatus(data.text);else if(data.type==='result'){clearTimeout(aiTimeout.current);setAiResults(rankPlaces(candidates,data.scores));setAiState('done');setView('explore');setSelected(null);}else{stopAI();setAiError(data.message);}};worker.current.onerror=()=>{stopAI();setAiError('이 브라우저에서 AI를 실행하지 못했어요. 거리순 검색은 계속 사용할 수 있어요.');};worker.current.postMessage({id,query:aiQuery.slice(0,300),texts:candidates.map(placeText)});clearTimeout(aiTimeout.current);aiTimeout.current=setTimeout(()=>{stopAI();setAiError('AI 준비 시간이 길어지고 있어요. Wi-Fi에서 다시 실행해 주세요.');},240000);}catch{stopAI();setAiError('이 브라우저에서 AI를 시작하지 못했어요.');}
 }
 const selectedSaved=selected&&saved.some(p=>p.id===selected.id);
 if(demo)return <><div className="demo-return"><button onClick={()=>setDemo(false)}><ArrowLeft size={20}/>실제 주변 탐색으로</button><span>주문·결제 시연</span></div><Demo/></>;
 return <div className="discover">
  <header className="dd-header"><a className="dd-brand" href={import.meta.env.BASE_URL}><span>D</span>당도</a><nav aria-label="주요 메뉴"><button className={view==='explore'?'active':''} onClick={()=>{setView('explore');setSelected(null);}}><Compass size={20}/>주변 탐색</button><button className={view==='saved'?'active':''} onClick={()=>{setView('saved');setSelected(null);setFilter('전체');}}><Bookmark size={20}/>저장한 곳{saved.length>0&&<span className="nav-count">{saved.length}</span>}</button></nav><button className="settings-button" aria-label="설정" onClick={()=>setDialog('settings')}><SlidersHorizontal size={21}/><span>설정</span></button></header>
  <main className="dd-layout">
   <section className="map-stage"><LiveMap key={key||'osm'} center={center} places={shown} selected={selected} onSelect={setSelected} onMove={setMoved} gps={gps} kakaoKey={key} onError={msg=>{setNotice(msg);if(key){setKey('');write('dangdo.kakao-key','');}}}/>
    <div className="map-caption-live"><span className="provider-dot"/>{key?'카카오맵':'OpenStreetMap'}<span className="caption-divider"/>{area.name} 주변</div>
    {moved&&<button className="search-here" onClick={()=>chooseArea({...moved,name:'선택한 지도 위치'})}><Search size={17}/>이 위치에서 검색</button>}
    <button className={`gps-button ${locating?'locating':''}`} onClick={()=>gps?locate():setDialog('location')} disabled={locating} aria-label="내 위치로 이동">{locating?<LoaderCircle className="spin"/>:<LocateFixed/>}</button>
    <div className="map-legend"><span className="legend-pin">1</span>식당 위치{gps&&<><span className="legend-gps"/>내 위치</>}</div>
   </section>
   <section className="explore-panel" aria-label="식당 탐색">
    <div className="panel-top"><div className="panel-kicker">이동의 끝, 맛있는 시작</div><h1>{view==='saved'?'다음에 갈 곳':'어디에 도착하나요?'}</h1>
     <form className="destination-search" onSubmit={findArea}><Search size={21}/><input aria-label="목적지 검색" placeholder="목적지, 동네 이름 검색" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button type="submit" disabled={searchBusy||!query.trim()} aria-label="장소 검색">{searchBusy?<LoaderCircle className="spin" size={20}/>:<ChevronRight size={22}/>}</button></form>
     {searchError&&<p className="inline-error" role="alert">{searchError}</p>}
     {areaResults!==null&&<div className="area-results"><div className="results-title">검색 결과<button onClick={()=>setAreaResults(null)} aria-label="검색 결과 닫기"><X size={18}/></button></div>{areaResults.length?areaResults.map((p,i)=><button className="area-result" key={i} onClick={()=>chooseArea(p)}><MapPin size={19}/><span><strong>{p.name}</strong><span>{p.address}</span></span></button>):<p>검색 결과가 없어요. 지역명을 함께 입력해 주세요.</p>}</div>}
     <div className="area-shortcuts"><button className="my-location" onClick={()=>gps?locate():setDialog('location')} disabled={locating}>{locating?<LoaderCircle size={16} className="spin"/>:<LocateFixed size={16}/>}내 위치</button>{AREAS.slice(0,3).map(p=><button key={p.name} onClick={()=>chooseArea(p)} className={area.name===p.name?'chosen':''}>{p.name}</button>)}</div>
    </div>
    <div hidden={view!=='explore'}><Journey area={area} gps={gps} kakaoKey={key} onDestination={chooseArea} onGPS={setGps} onActiveDestination={setActiveDestination} onConnect={()=>setDialog('settings')} Dialog={Dialog}/></div>
    {view==='explore'&&<section className="ai-box"><div className="ai-title"><span><Sparkles size={19}/>오늘은 뭐 먹지?</span><span className="ai-label">AI 추천</span></div><form onSubmit={e=>{e.preventDefault();if(aiState!=='working')setDialog('ai');}}><input aria-label="먹고 싶은 음식" placeholder="예: 가까운 한식집이나 국수" maxLength={300} value={aiQuery} onChange={e=>setAiQuery(e.target.value)} disabled={aiState==='working'}/><button disabled={!aiQuery.trim()||busy||!places.length||aiState==='working'} aria-label="AI 추천 시작"><Sparkles size={21}/></button></form>{aiState==='working'?<div className="ai-progress" role="status"><LoaderCircle size={16} className="spin"/><span>{aiStatus}</span><button onClick={stopAI}>취소</button></div>:aiResults?<div className="ai-progress"><Check size={16}/><span>취향과 거리를 함께 비교했어요</span><button onClick={()=>{setAiResults(null);setAiState('idle');}}>해제</button></div>:<div className="prompt-shortcuts">{['한식 한 끼','커피 한 잔','피자·버거'].map(x=><button key={x} onClick={()=>setAiQuery(x)}>{x}</button>)}</div>}{aiError&&<p className="inline-error" role="alert">{aiError}</p>}</section>}
    <div className="list-controls"><div><h2>{view==='saved'?'저장한 곳':aiResults?'취향에 맞는 곳':'주변에서 찾았어요'}</h2><span>{busy&&view==='explore'?'검색 중':`${shown.length}곳`}</span></div><div className="filter-row"><div className="category-tabs">{['전체','음식점','카페'].map(x=><button key={x} aria-pressed={filter===x} className={filter===x?'selected':''} onClick={()=>{setFilter(x);setSelected(null);setAiResults(null);stopAI();}}>{x}</button>)}</div>{view==='explore'&&<select aria-label="검색 반경" value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={500}>500m</option><option value={1500}>1.5km</option><option value={3000}>3km</option></select>}</div></div>
    <div className="restaurant-list" aria-live="polite">
     {busy&&view==='explore'?<div className="list-state"><LoaderCircle className="spin" size={30}/><h3>주변 식당을 찾고 있어요</h3><p>실제 장소 정보를 불러오는 중이에요.</p></div>:error&&view==='explore'?<div className="list-state"><MapIcon size={32}/><h3>검색이 잠시 지연되고 있어요</h3><p>{error}</p><button className="dd-primary" onClick={()=>setRefresh(n=>n+1)}>다시 검색</button><a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(area.name+' 음식점')}`}>카카오맵에서 찾기</a></div>:!shown.length?<div className="list-state"><Bookmark size={32}/><h3>{view==='saved'?'가고 싶은 곳을 저장해 보세요':'이 주변에는 등록된 식당이 없어요'}</h3><p>{view==='saved'?'식당 카드의 저장 버튼을 눌러 보세요.':'검색 반경을 넓히거나 다른 위치를 선택해 주세요.'}</p>{view==='explore'&&<a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(area.name+' 음식점')}`}>카카오맵에서 찾기</a>}</div>:shown.map((p,i)=><article key={p.id} className={`restaurant-card ${selected?.id===p.id?'selected':''}`}><button className="restaurant-open" onClick={()=>setSelected(p)} aria-label={`${p.name} 상세 보기`}><span className={`restaurant-symbol ${p.kind==='카페'?'cafe':''}`}><Icon place={p} size={26}/><span>{i+1}</span></span><span className="restaurant-info"><span className="restaurant-category">{p.category}</span><strong>{p.name}</strong><span className="restaurant-distance"><MapPin size={14}/>{view==='saved'?'저장한 장소':`직선 ${distanceLabel(p.distance)}`}{aiResults&&view!=='saved'&&i<3&&<span className="match-label">AI 추천</span>}</span></span></button><button className={`save-place ${saved.some(x=>x.id===p.id)?'saved':''}`} onClick={()=>toggleSave(p)} aria-label={`${p.name} ${saved.some(x=>x.id===p.id)?'저장 취소':'저장'}`} aria-pressed={saved.some(x=>x.id===p.id)}><Bookmark size={21}/></button></article>)}
    </div>
    <footer className="panel-footer"><span>{view==='saved'?'이 기기에 저장됨':`${key?'카카오맵':'OpenStreetMap'} 장소 정보 · ${aiResults?'AI 추천순':'거리순'}`}</span><button onClick={()=>setDialog('about')}>이용 안내</button></footer>
   </section>
  </main>
  {selected&&<Dialog title="장소 정보" onClose={()=>setSelected(null)}><div className="place-detail"><div className="detail-icon"><Icon place={selected} size={32}/></div><p className="detail-category">{selected.category}</p><h2>{selected.name}</h2>{view!=='saved'&&<p className="detail-distance">{area.name}에서 직선 {distanceLabel(selected.distance)}</p>}<div className="detail-facts"><p><MapPin size={19}/><span>{selected.address||'주소는 카카오맵에서 확인할 수 있어요'}</span></p>{selected.phone&&<p><Phone size={19}/><a href={`tel:${selected.phone.replace(/[^+\d]/g,'')}`}>{selected.phone}</a></p>}</div><div className="travel-options" aria-label="이동 수단">{[['walk','도보',Footprints],['car','자동차',Car],['traffic','대중교통',Bus]].map(([id,label,Component])=><button key={id} className={travel===id?'selected':''} onClick={()=>setTravel(id)} aria-pressed={travel===id}><Component size={19}/>{label}</button>)}</div><a className="dd-primary" target="_blank" rel="noopener noreferrer" href={routeURL(selected,gps||center,travel)}><Navigation size={19}/>카카오맵 길찾기</a><div className="detail-buttons"><button className="dd-secondary" onClick={()=>toggleSave(selected)}><Bookmark size={18} fill={selectedSaved?'currentColor':'none'}/>{selectedSaved?'저장했어요':'저장'}</button><a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(selected.name+' '+(selected.address||''))}`}>메뉴·리뷰 확인<ExternalLink size={16}/></a></div><p className="detail-source">{selected.source} 등록 정보 · 영업 여부는 방문 전 확인해 주세요.</p></div></Dialog>}
  {dialog==='location'&&<Dialog title="내 주변을 찾아볼까요?" onClose={()=>setDialog(null)}><div className="dialog-body"><div className="location-art"><LocateFixed size={36}/></div><p>현재 위치로 가까운 식당을 찾아요. 검색 좌표는 지도·장소 제공업체로 전송되며 당도에 저장하지 않아요.</p><button className="dd-primary" onClick={()=>{setDialog(null);locate();}}>현재 위치 사용</button><button className="dd-secondary" onClick={()=>setDialog(null)}>목적지 직접 검색</button></div></Dialog>}
  {dialog==='ai'&&<Dialog title="AI로 취향 찾기" onClose={()=>setDialog(null)}><div className="dialog-body"><div className="location-art"><Sparkles size={36}/></div><p>“{aiQuery}”에 맞춰 주변 장소의 이름·업종과 거리를 비교해요.</p><p>처음 실행할 때 AI 모델을 다운로드해요. Wi-Fi 사용을 권장해요. 추천은 기기 안에서 실행돼요.</p><p className="muted-text">가격·혼잡도·알레르기 정보는 확인할 수 없어요.</p><button className="dd-primary" onClick={()=>{setDialog(null);startAI();}}>모델을 불러와 추천받기</button></div></Dialog>}
  {dialog==='settings'&&<Dialog title="설정" onClose={()=>setDialog(null)}><div className="dialog-body"><h3>카카오맵 연결</h3><p>카카오 개발자 설정에서 앱을 선택하고 카카오맵 사용을 활성화하세요. 플랫폼 키의 JavaScript 키에 아래 도메인을 등록한 뒤 키를 입력하면 지도·장소 검색·내비 출발을 연결해요.</p><label className="setting-label">JavaScript 키<input value={keyDraft} onChange={e=>setKeyDraft(e.target.value)} placeholder="JavaScript 키 입력" autoComplete="off"/></label><p className="muted-text">등록 도메인: {location.origin}<br/>REST API 키·Admin 키는 입력하지 마세요.</p><button className="dd-primary" onClick={()=>{const next=keyDraft.trim();if(next&&!/^[a-f0-9]{32}$/i.test(next)){setNotice('32자리 JavaScript 키를 확인해 주세요.');return;}write('dangdo.kakao-key',next);location.reload();}}>{keyDraft.trim()?'카카오맵 연결':'공개 지도 사용'}</button><a className="settings-link" href="https://developers.kakao.com/console/app" target="_blank" rel="noopener noreferrer">카카오 개발자 설정 열기<ExternalLink size={16}/></a><hr/><button className="setting-row" onClick={()=>{setDialog(null);setDemo(true);}}>주문·혜택·가맹점 시연<ChevronRight size={20}/></button><button className="setting-row" onClick={()=>setDialog('about')}>이용 안내<ChevronRight size={20}/></button></div></Dialog>}
  {dialog==='about'&&<Dialog title="당도 이용 안내" onClose={()=>setDialog(null)}><div className="dialog-body"><h3>실제 장소를 탐색해요</h3><p>GPS, 주변 장소 조회, 카카오맵 길찾기는 실제 기능이에요. 공개 지도는 지역에 따라 식당 정보가 부족할 수 있어요.</p><h3>AI는 취향과 업종을 비교해요</h3><p>다국어 MiniLM 모델이 장소 이름·업종과 입력 문장의 의미를 비교하고 거리를 함께 반영해요. 리뷰·메뉴·가격·분위기를 검증하는 모델은 아니에요.</p><h3>위치와 저장</h3><p>위치는 사용자가 허용할 때만 가져와요. GPS 좌표는 저장하지 않으며 지도·검색 제공업체에 전송돼요. 저장한 식당과 지도 설정은 이 브라우저에 남아요.</p><h3>이동과 주문</h3><p>카카오 T 탑승·ETA 자동 연동과 실제 주문·결제는 지원하지 않아요. 기존 주문 시연은 설정에서 볼 수 있어요.</p><a className="settings-link" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap 기여자 · ODbL<ExternalLink size={16}/></a></div></Dialog>}
  {notice&&<div className="dd-toast" role="status">{notice}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
