import './base.css';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Search,Navigation,LocateFixed,SlidersHorizontal,Sparkles,Bookmark,Compass,X,ChevronRight,ArrowLeft,Utensils,Coffee,LoaderCircle,Phone,Check,Map as MapIcon,Car,Footprints,Bus,Plus,ExternalLink} from 'lucide-react';
import LiveMap from './LiveMap.jsx';
import Journey from './Journey.jsx';
import {destinationFromURL} from './journeyModel.js';
import './journey.css';
import {nearbyOSM,nearbyKakao,loadKakao,searchArea,distanceLabel,routeURL,placeText,rankPlaces} from './places.js';
import './discover.css';
import './onboarding.css';
import MobilityPanel from './MobilityPanel.jsx';
import TalkHome from './TalkHome.jsx';
import DeviceAccount from './DeviceAccount.jsx';
import {readDevice,forgetDevice} from './deviceAccount.js';
import {loadNavi} from './kakaoNavi.js';
import {destinationShare,sendDestination} from './destinationShare.js';
import {api,apiBase,readAuthReturn,clearAuthReturn} from './auth.js';
import {rankArrivalPlaces} from './ranking.js';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
const Icon=({place,...props})=>place.kind==='카페'?<Coffee {...props}/>:<Utensils {...props}/>;
function Dialog({title,onClose,children}){const ref=useRef();useEffect(()=>{ref.current.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="dd-dialog" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-label={title}><div className="dialog-heading"><h2>{title}</h2><button className="round-button" onClick={onClose} aria-label="닫기"><X/></button></div>{children}</dialog>}
function App(){
 const [home,setHome]=useState(()=>!destinationFromURL(location.href));
 useEffect(()=>{localStorage.removeItem('dangdo.kakao-key');},[]);
 const [user,setUser]=useState(readDevice),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(''),[loginReady,setLoginReady]=useState(false),[mobilityMode,setMobilityMode]=useState('walk'),[insights,setInsights]=useState(null);
 useEffect(()=>{let dead=false;const controller=new AbortController();(async()=>{try{if(apiBase()){const conf=await api('/api/config',{signal:controller.signal});if(!dead)setLoginReady(conf.login);}const returned=readAuthReturn(location.hash);if(returned.ticket){clearAuthReturn();setAuthBusy(true);const result=await api('/api/auth/exchange',{method:'POST',body:JSON.stringify({ticket:returned.ticket}),signal:controller.signal});sessionStorage.setItem('dangdo.session',result.session);if(!dead){setUser(result.user);enter();}}else if(returned.error){clearAuthReturn();setAuthError(returned.error==='cancelled'?'로그인을 취소했어요. 다시 시작하거나 먼저 둘러볼 수 있어요.':'로그인 연결을 다시 확인해 주세요.');}else if(sessionStorage.getItem('dangdo.session')){const result=await api('/api/me',{signal:controller.signal});if(!dead){setUser(result.user);enter();}}}catch(e){if(!dead){setAuthError(e.message);sessionStorage.removeItem('dangdo.session');}}finally{if(!dead)setAuthBusy(false);}})();return()=>{dead=true;controller.abort();};},[]);
 function enter(){setHome(true);}
 function login(){if(!loginReady){setAuthError('로그인 서버 연결을 준비하고 있어요. 먼저 둘러볼 수 있어요.');return;}setAuthBusy(true);location.assign(apiBase()+'/api/auth/start');}
 async function logout(){if(user?.kind!=='device')try{await api('/api/auth/logout',{method:'POST'});}catch{}forgetDevice();sessionStorage.removeItem('dangdo.session');sessionStorage.removeItem('dangdo.entered');setUser(null);setHome(true);setDialog(null);}

 const [area,setArea]=useState(()=>destinationFromURL(location.href)||null),[center,setCenter]=useState(()=>destinationFromURL(location.href)||null),[moved,setMoved]=useState(null),[gps,setGps]=useState(null),[locating,setLocating]=useState(false),[places,setPlaces]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('전체'),[selected,setSelected]=useState(null),[radius,setRadius]=useState(1500),[refresh,setRefresh]=useState(0),[query,setQuery]=useState(''),[areaResults,setAreaResults]=useState(null),[searchBusy,setSearchBusy]=useState(false),[searchError,setSearchError]=useState(''),[view,setView]=useState('explore'),[saved,setSaved]=useState(()=>read('dangdo.saved',[])),[dialog,setDialog]=useState(null),[key,setKey]=useState(()=>import.meta.env.VITE_KAKAO_MAP_KEY||''),[aiQuery,setAiQuery]=useState(''),[aiState,setAiState]=useState('idle'),[aiStatus,setAiStatus]=useState(''),[aiResults,setAiResults]=useState(null),[aiError,setAiError]=useState(''),[travel,setTravel]=useState('walk');
 const [activeDestination,setActiveDestination]=useState(null);
 const searchAbort=useRef(),searchSequence=useRef(0),worker=useRef(),aiId=useRef(0),aiTimeout=useRef(),gpsSequence=useRef(0);
 function stopAI(){aiId.current++;clearTimeout(aiTimeout.current);worker.current?.terminate();worker.current=null;setAiState('idle');setAiStatus('');}
 useEffect(()=>{write('dangdo.saved',saved);},[saved]);
 useEffect(()=>{if(!notice||!area)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice,area]);
 useEffect(()=>()=>{searchAbort.current?.abort();worker.current?.terminate();clearTimeout(aiTimeout.current);gpsSequence.current++;},[]);
 useEffect(()=>{if(!center)return;const controller=new AbortController();let dead=false;setBusy(true);setError('');setPlaces([]);setSelected(null);setAiResults(null);setAiError('');stopAI();
  (async()=>{try{let rows;if(key){try{rows=await nearbyKakao(await loadKakao(key),center,radius);}catch(e){if(dead)return;setNotice('카카오 연결을 확인해 주세요. 공개 지도로 전환했어요.');setKey('');return;}}else rows=await nearbyOSM(center,radius,controller.signal);if(!dead)setPlaces(rows);}catch(e){if(!dead)setError('주변 식당을 불러오지 못했어요. 잠시 후 다시 검색해 주세요.');}finally{if(!dead)setBusy(false);}})();return()=>{dead=true;controller.abort();};
 },[center,radius,refresh,key]);
 const shown=useMemo(()=>{const source=view==='saved'?saved:(aiResults||rankArrivalPlaces(places,{mode:mobilityMode}));return source.filter(p=>filter==='전체'||(filter==='카페'?p.kind==='카페':p.kind!=='카페'));},[places,aiResults,saved,filter,view,mobilityMode]);
 function chooseArea(p){setHome(false);if(!area)localStorage.removeItem('dangdo.journey');searchSequence.current++;searchAbort.current?.abort();setSearchBusy(false);setArea(p);setCenter(p);setMoved(null);setAreaResults(null);setQuery('');setView('explore');setSelected(null);}
 async function findArea(e){e.preventDefault();if(!query.trim()||searchBusy)return;const seq=++searchSequence.current;searchAbort.current?.abort();searchAbort.current=new AbortController();setSearchBusy(true);setSearchError('');try{const results=await searchArea(query.trim(),key,searchAbort.current.signal);if(seq===searchSequence.current)setAreaResults(results);}catch(e){if(seq===searchSequence.current&&e.name!=='AbortError')setSearchError('장소 검색에 실패했어요. 다시 시도해 주세요.');}finally{if(seq===searchSequence.current)setSearchBusy(false);}}
 function locate(){if(!navigator.geolocation){setNotice('이 브라우저는 위치 기능을 지원하지 않아요. 목적지를 검색해 주세요.');return;}const seq=++gpsSequence.current;setLocating(true);navigator.geolocation.getCurrentPosition(p=>{if(seq!==gpsSequence.current)return;const point={name:'내 위치',lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};setGps(point);if(!activeDestination)chooseArea(point);setLocating(false);if(p.coords.accuracy>200)setNotice('위치 오차가 커요. 지도에서 검색할 위치를 조정할 수 있어요.');},e=>{if(seq!==gpsSequence.current)return;setLocating(false);setNotice(e.code===1?'위치 권한이 꺼져 있어요. 브라우저 설정에서 허용하거나 목적지를 검색해 주세요.':e.code===3?'위치를 확인하는 데 시간이 걸려요. 다시 시도해 주세요.':'위치를 확인하지 못했어요. 목적지를 검색해 주세요.');},{enableHighAccuracy:true,timeout:15000,maximumAge:30000});}
 function toggleSave(p){setSaved(prev=>prev.some(x=>x.id===p.id)?prev.filter(x=>x.id!==p.id):[p,...prev].slice(0,100));}
 function startAI(){if(!aiQuery.trim()||!places.length||aiState==='working')return;const candidates=places.filter(p=>filter==='전체'||(filter==='카페'?p.kind==='카페':p.kind!=='카페')).slice(0,30);if(!candidates.length){setAiError('이 종류의 식당이 없어요. 다른 종류를 선택해 주세요.');return;}setAiError('');setAiResults(null);setAiState('working');setAiStatus('AI 모델 준비 중');const id=++aiId.current;
  try{worker.current ||= new Worker(new URL('./recommend.worker.js',import.meta.url),{type:'module'});worker.current.onmessage=({data})=>{if(data.id!==aiId.current)return;if(data.type==='progress')setAiStatus(data.text);else if(data.type==='result'){clearTimeout(aiTimeout.current);setAiResults(rankArrivalPlaces(candidates,{scores:data.scores,mode:mobilityMode}));setAiState('done');setView('explore');setSelected(null);}else{stopAI();setAiError(data.message);}};worker.current.onerror=()=>{stopAI();setAiError('이 브라우저에서 AI를 실행하지 못했어요. 거리순 검색은 계속 사용할 수 있어요.');};worker.current.postMessage({id,query:aiQuery.slice(0,300),texts:candidates.map(placeText)});clearTimeout(aiTimeout.current);aiTimeout.current=setTimeout(()=>{stopAI();setAiError('AI 준비 시간이 길어지고 있어요. Wi-Fi에서 다시 실행해 주세요.');},240000);}catch{stopAI();setAiError('이 브라우저에서 AI를 시작하지 못했어요.');}
 }
 useEffect(()=>{if(key)loadNavi(key).catch(()=>{});},[key]);
 async function sharePlace(place=area){try{const result=await sendDestination(destinationShare(location.origin+import.meta.env.BASE_URL,place),window.Kakao,navigator);if(result==='copied')setNotice('공유 링크를 복사했어요. 카카오톡에 붙여 넣어 보내세요.');}catch(e){if(e.name!=='AbortError')setNotice('공유하지 못했어요. 다시 시도해 주세요.');}}
 const sharedOverlay=<>{dialog==='account'&&<DeviceAccount user={user} onUser={setUser} onLogout={logout} Dialog={Dialog} onClose={()=>setDialog(null)} kakaoReady={loginReady} onKakao={login}/>} {dialog==='settings'&&<Dialog title="설정" onClose={()=>setDialog(null)}><div className="dialog-body"><button className="setting-row" onClick={()=>setDialog('account')}>내 프로필<ChevronRight size={20}/></button><a className="setting-row" href="https://kakaopay.com/services/life/payment" target="_blank" rel="noopener noreferrer">카카오페이<ExternalLink size={20}/></a><p>위치 사용은 GPS 버튼을 누를 때 선택해요. 당도 계정은 이 기기 브라우저에 저장되며 다른 기기와 동기화되지 않아요.</p><p className="muted-text">당도는 카카오의 공식 앱이 아닌 독립 서비스입니다.</p></div></Dialog>}</>;
 if(home||!area)return <><TalkHome user={user} onAccount={()=>setDialog('account')} onSettings={()=>setDialog('settings')} onGPS={locate} locating={locating} query={query} onQuery={setQuery} onSearch={findArea} searchBusy={searchBusy} searchError={searchError} notice={notice||authError} results={areaResults} onChoose={chooseArea} mode={mobilityMode} onMode={setMobilityMode} saved={saved} onSaved={chooseArea} onExplore={area?()=>setHome(false):null} onShare={()=>sharePlace()}/>{sharedOverlay}</>;
 const selectedSaved=selected&&saved.some(p=>p.id===selected.id);
 return <div className="discover">
  <header className="dd-header"><button className="dd-brand" onClick={()=>setHome(true)}><span>D</span><div className="brand-stack"><small className="header-wordmark">kakao mobility</small><strong className="header-title">당도</strong></div></button><nav aria-label="주요 메뉴"><button className={view==='explore'?'active':''} onClick={()=>{setView('explore');setSelected(null);}}><Compass size={20}/>주변 탐색</button><button className={view==='saved'?'active':''} onClick={()=>{setView('saved');setSelected(null);setFilter('전체');}}><Bookmark size={20}/>저장한 곳{saved.length>0&&<span className="nav-count">{saved.length}</span>}</button></nav><button className="account-button" aria-label={user?"내 프로필":"로그인"} onClick={()=>setDialog('account')}>{user?.picture?<img src={user.picture} alt="내 프로필 사진" referrerPolicy="no-referrer"/>:<span className="account-avatar">{user?user.nickname.slice(0,1):'↗'}</span>}<span>{user?user.nickname:'로그인'}</span></button><button className="settings-button" aria-label="설정" onClick={()=>setDialog('settings')}><SlidersHorizontal size={21}/><span>설정</span></button></header>
  <main className="dd-layout">
   <section className="map-stage"><LiveMap key={key||'osm'} center={center} places={shown} selected={selected} onSelect={setSelected} onMove={setMoved} gps={gps} kakaoKey={key} onError={msg=>{setNotice(msg);if(key){setKey('');}}}/>
    <div className="map-caption-live"><span className="provider-dot"/>{key?'카카오맵':'OpenStreetMap'}<span className="caption-divider"/>{area.name} 주변</div>
    {moved&&<button className="search-here" onClick={()=>chooseArea({...moved,name:'선택한 지도 위치'})}><Search size={17}/>이 위치에서 검색</button>}
    <button className={`gps-button ${locating?'locating':''}`} onClick={()=>gps?locate():setDialog('location')} disabled={locating} aria-label="내 위치로 이동">{locating?<LoaderCircle className="spin"/>:<LocateFixed/>}</button>
    <div className="map-legend"><span className="legend-pin">1</span>식당 위치{gps&&<><span className="legend-gps"/>내 위치</>}</div>
   </section>
   <section className="explore-panel" aria-label="식당 탐색">
    <div className="panel-top"><div className="panel-kicker">이동의 끝, 맛있는 시작</div><button className="destination-share" onClick={()=>sharePlace()}>목적지 카카오톡 공유</button><h1>{view==='saved'?'다음에 갈 곳':'어디에 도착하나요?'}</h1>
     <form className="destination-search" onSubmit={findArea}><Search size={21}/><input aria-label="목적지 검색" placeholder="목적지, 동네 이름 검색" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button type="submit" disabled={searchBusy||!query.trim()} aria-label="장소 검색">{searchBusy?<LoaderCircle className="spin" size={20}/>:<ChevronRight size={22}/>}</button></form>
     {searchError&&<p className="inline-error" role="alert">{searchError}</p>}
     {areaResults!==null&&<div className="area-results"><div className="results-title">검색 결과<button onClick={()=>setAreaResults(null)} aria-label="검색 결과 닫기"><X size={18}/></button></div>{areaResults.length?areaResults.map((p,i)=><button className="area-result" key={i} onClick={()=>chooseArea(p)}><MapPin size={19}/><span><strong>{p.name}</strong><span>{p.address}</span></span></button>):<p>검색 결과가 없어요. 지역명을 함께 입력해 주세요.</p>}</div>}
     <div className="area-shortcuts"><button className="my-location" onClick={()=>gps?locate():setDialog('location')} disabled={locating}>{locating?<LoaderCircle size={16} className="spin"/>:<LocateFixed size={16}/>}내 위치</button></div>
    </div>
    {view==='explore'&&<MobilityPanel area={activeDestination||area} gps={gps} kakaoKey={key} mode={mobilityMode} onMode={setMobilityMode} onStart={()=>document.querySelector('.journey-start')?.click()} onNotice={setNotice} onInsights={setInsights}/>}
    <a className="real-pay-entry" href="https://kakaopay.com/services/life/payment" target="_blank" rel="noopener noreferrer"><b>pay</b><span>카카오페이 열기</span><ExternalLink size={20}/></a>
    <div hidden={view!=='explore'}><Journey area={area} gps={gps} kakaoKey={key} onDestination={chooseArea} onGPS={setGps} onActiveDestination={setActiveDestination} onConnect={()=>setDialog('settings')} Dialog={Dialog}/></div>
    {view==='explore'&&<section className="ai-box"><div className="ai-title"><span><Sparkles size={19}/>오늘은 뭐 먹지?</span><span className="ai-label">AI 추천</span></div><form onSubmit={e=>{e.preventDefault();if(aiState!=='working')setDialog('ai');}}><input aria-label="먹고 싶은 음식" placeholder="예: 가까운 한식집이나 국수" maxLength={300} value={aiQuery} onChange={e=>setAiQuery(e.target.value)} disabled={aiState==='working'}/><button disabled={!aiQuery.trim()||busy||!places.length||aiState==='working'} aria-label="AI 추천 시작"><Sparkles size={21}/></button></form>{aiState==='working'?<div className="ai-progress" role="status"><LoaderCircle size={16} className="spin"/><span>{aiStatus}</span><button onClick={stopAI}>취소</button></div>:aiResults?<div className="ai-progress"><Check size={16}/><span>취향과 거리를 함께 비교했어요</span><button onClick={()=>{setAiResults(null);setAiState('idle');}}>해제</button></div>:<div className="prompt-shortcuts">{['한식 한 끼','커피 한 잔','피자 버거'].map(x=><button key={x} onClick={()=>setAiQuery(x)}>{x}</button>)}</div>}{aiError&&<p className="inline-error" role="alert">{aiError}</p>}</section>}
    <div className="list-controls"><div><h2>{view==='saved'?'저장한 곳':aiResults?'취향에 맞는 곳':'주변에서 찾았어요'}</h2><span>{busy&&view==='explore'?'검색 중':`${shown.length}곳`}</span></div><div className="filter-row"><div className="category-tabs">{['전체','음식점','카페'].map(x=><button key={x} aria-pressed={filter===x} className={filter===x?'selected':''} onClick={()=>{setFilter(x);setSelected(null);setAiResults(null);stopAI();}}>{x}</button>)}</div>{view==='explore'&&<select aria-label="검색 반경" value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={500}>500m</option><option value={1500}>1.5km</option><option value={3000}>3km</option></select>}</div></div>
    <div className="restaurant-list" aria-live="polite">
     {busy&&view==='explore'?<div className="list-state"><LoaderCircle className="spin" size={30}/><h3>주변 식당을 찾고 있어요</h3><p>실제 장소 정보를 불러오는 중이에요.</p></div>:error&&view==='explore'?<div className="list-state"><MapIcon size={32}/><h3>검색이 잠시 지연되고 있어요</h3><p>{error}</p><button className="dd-primary" onClick={()=>setRefresh(n=>n+1)}>다시 검색</button><a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(area.name+' 음식점')}`}>카카오맵에서 찾기</a></div>:!shown.length?<div className="list-state"><Bookmark size={32}/><h3>{view==='saved'?'가고 싶은 곳을 저장해 보세요':'이 주변에는 등록된 식당이 없어요'}</h3><p>{view==='saved'?'식당 카드의 저장 버튼을 눌러 보세요.':'검색 반경을 넓히거나 다른 위치를 선택해 주세요.'}</p>{view==='explore'&&<a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(area.name+' 음식점')}`}>카카오맵에서 찾기</a>}</div>:shown.map((p,i)=><article key={p.id} className={`restaurant-card ${selected?.id===p.id?'selected':''}`}><button className="restaurant-open" onClick={()=>setSelected(p)} aria-label={`${p.name} 상세 보기`}><span className={`restaurant-symbol ${p.kind==='카페'?'cafe':''}`}><Icon place={p} size={26}/><span>{i+1}</span></span><span className="restaurant-info"><span className="restaurant-category">{p.category}</span><strong>{p.name}</strong><span className="restaurant-distance"><MapPin size={14}/>{view==='saved'?'저장한 장소':`직선 ${distanceLabel(p.distance)}`}{view!=='saved'&&p.accessEstimateMinutes&&<span className="arrival-estimate" title="직선 거리로 계산한 추정치예요. 실제 길 안내 시간과 다를 수 있어요.">{p.accessEstimateMode} 약 {p.accessEstimateMinutes}분</span>}{aiResults&&view!=='saved'&&i<3&&<span className="match-label">AI 추천</span>}</span></span></button><button className={`save-place ${saved.some(x=>x.id===p.id)?'saved':''}`} onClick={()=>toggleSave(p)} aria-label={`${p.name} ${saved.some(x=>x.id===p.id)?'저장 취소':'저장'}`} aria-pressed={saved.some(x=>x.id===p.id)}><Bookmark size={21}/></button></article>)}
    </div>
    <footer className="panel-footer"><span>{view==='saved'?'이 기기에 저장됨':`${key?'카카오맵':'OpenStreetMap'} 장소 정보   ${aiResults?'AI 추천순':'이동 거리순'}`}</span><button onClick={()=>setDialog('about')}>이용 안내</button></footer>
   </section>
  </main>
  {selected&&<Dialog title="장소 정보" onClose={()=>setSelected(null)}><div className="place-detail"><div className="detail-icon"><Icon place={selected} size={32}/></div><p className="detail-category">{selected.category}</p><h2>{selected.name}</h2>{view!=='saved'&&<p className="detail-distance">{area.name}에서 직선 {distanceLabel(selected.distance)}</p>}<div className="detail-facts"><p><MapPin size={19}/><span>{selected.address||'주소는 카카오맵에서 확인할 수 있어요'}</span></p>{selected.phone&&<p><Phone size={19}/><a href={`tel:${selected.phone.replace(/[^+\d]/g,'')}`}>{selected.phone}</a></p>}</div><div className="travel-options" aria-label="이동 수단">{[['walk','도보',Footprints],['car','자동차',Car],['traffic','대중교통',Bus]].map(([id,label,Component])=><button key={id} className={travel===id?'selected':''} onClick={()=>setTravel(id)} aria-pressed={travel===id}><Component size={19}/>{label}</button>)}</div><a className="dd-primary" target="_blank" rel="noopener noreferrer" href={routeURL(selected,gps||center,travel)}><Navigation size={19}/>카카오맵 길찾기</a><div className="detail-buttons"><button className="dd-secondary" onClick={()=>toggleSave(selected)}><Bookmark size={18} fill={selectedSaved?'currentColor':'none'}/>{selectedSaved?'저장했어요':'저장'}</button><a className="dd-secondary" target="_blank" rel="noopener noreferrer" href={`https://map.kakao.com/link/search/${encodeURIComponent(selected.name+' '+(selected.address||''))}`}>메뉴 리뷰 확인<ExternalLink size={16}/></a></div><button className="dd-secondary" onClick={()=>sharePlace(selected)}>카카오톡으로 공유</button><p className="detail-source">{selected.source} 등록 정보   영업 여부는 방문 전 확인해 주세요.</p></div></Dialog>}
  {dialog==='location' &&<Dialog title="내 주변을 찾아볼까요?" onClose={()=>setDialog(null)}><div className="dialog-body"><div className="location-art"><LocateFixed size={36}/></div><p>현재 위치로 가까운 식당을 찾아요. 검색 좌표는 지도 장소 제공업체로 전송되며 당도에 저장하지 않아요.</p><button className="dd-primary" onClick={()=>{setDialog(null);locate();}}>현재 위치 사용</button><button className="dd-secondary" onClick={()=>setDialog(null)}>목적지 직접 검색</button></div></Dialog>}
  {dialog==='ai'&&<Dialog title="AI로 취향 찾기" onClose={()=>setDialog(null)}><div className="dialog-body"><div className="location-art"><Sparkles size={36}/></div><p>“{aiQuery}”에 맞춰 주변 장소의 이름 업종과 거리를 비교해요.</p><p>처음 실행할 때 AI 모델을 다운로드해요. Wi-Fi 사용을 권장해요. 추천은 기기 안에서 실행돼요.</p><p className="muted-text">가격 혼잡도 알레르기 정보는 확인할 수 없어요.</p><button className="dd-primary" onClick={()=>{setDialog(null);startAI();}}>모델을 불러와 추천받기</button></div></Dialog>}
  {sharedOverlay}
  {dialog==='about'&&<Dialog title="당도 이용 안내" onClose={()=>setDialog(null)}><div className="dialog-body"><h3>실제 장소를 탐색해요</h3><p>GPS, 주변 장소 조회, 카카오맵 길찾기는 실제 기능이에요. 공개 지도는 지역에 따라 식당 정보가 부족할 수 있어요.</p><h3>AI는 취향과 업종을 비교해요</h3><p>다국어 MiniLM 모델이 장소 이름 업종과 입력 문장의 의미를 비교하고 거리를 함께 반영해요. 리뷰 메뉴 가격 분위기를 검증하는 모델은 아니에요.</p><h3>위치와 저장</h3><p>위치는 사용자가 허용할 때만 가져와요. GPS 좌표는 저장하지 않으며 지도 검색 제공업체에 전송돼요. 저장한 식당은 이 브라우저에 남아요.</p><h3>이동과 주문</h3><p>카카오 T 탑승 ETA 자동 연동과 실제 주문 결제는 지원하지 않아요. 결제수단과 거래내역은 카카오페이에서 확인할 수 있어요.</p><a className="settings-link" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap 기여자   ODbL<ExternalLink size={16}/></a></div></Dialog>}
  {notice&&<div className="dd-toast" role="status">{notice}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
