import React from 'react';
import OrbitSafety from './OrbitSafety.jsx';
import {MODES,formatTime} from './arrivalEngine.js';
export function MobilitySwitcher({journey,onChange}){return <div className="mobility-switcher" aria-label="이동수단 변경">{MODES.map(m=><button key={m.id} aria-pressed={journey.transportMode===m.id} onClick={()=>onChange(m.id)}>{m.id==='bike'?'바이크':m.name}</button>)}</div>;}
export function MobilityDetails({journey,onBike,onBoard,bikePreview,onBikePreview,compareBike,onCompareBike,bikeMap,onBikeRetry,onNavigationUpdate,onReroute}){const r=journey.route;if(journey.transportMode==='transit')return <section className="mobility-detail"><b>탑승 가능성이 높은 열차 기준</b><p>역까지 도보 {r.walkToStation}분 + 탑승 여유 {r.boardingBuffer}분</p><p>출발 시점 기준  2호선  다음 열차 {r.arrivals[0]}분 / 탑승 예정 {r.nextTrain}분</p><p>도보 → 열차 {r.ride}분 → 도보 {r.finalWalk}분</p><button className="arrival-secondary" disabled={r.boarded} onClick={onBoard}>{r.boarded?'열차 탑승 완료':'탑승 예정 열차에 탑승'}</button><details><summary>교통 정보</summary><p>예시 열차 시간표를 사용합니다.</p></details></section>;
 if(journey.transportMode==='bike')return <OrbitSafety journey={journey} onSelect={onBike} compare={compareBike} onCompare={onCompareBike} bikeMap={bikeMap} onRetry={onBikeRetry} onNavigationUpdate={onNavigationUpdate} onReroute={onReroute}/>;
 if(journey.transportMode==='wheelchair')return <section className="mobility-detail"><b>휠체어 이동</b><p>{r.status==='loading'?'계단을 피하는 경로를 찾고 있어요':r.status==='unavailable'?r.warning:`무장애 경로 선호 ${r.distanceKm.toFixed(1)} km`}</p>{r.status==='unavailable'&&<button className="arrival-secondary" onClick={()=>onBikeRetry('wheelchair')}>경로 다시 조회</button>}{r.steps?.length>0&&<details><summary>이동 경로 보기</summary>{r.steps.map((s,i)=><p key={i}>{s}</p>)}</details>}</section>;
 if(journey.transportMode==='walk')return <section className="mobility-detail"><b>도보 {r.distanceKm.toFixed(1)} km</b><p>예상 속도 {r.speedKmh.toFixed(1)} km/h</p></section>;
 return null;}
export function ArrivalSync({order,clock}){const p=order.sync;if(!p)return null;return <section className="sync-panel"><h2>사람과 상품,<br/>같은 도착시간</h2><div className="sync-grid"><div><span>내 도착</span><strong>{formatTime(order.arrival)}</strong></div><div><span>상품 준비</span><strong>{formatTime(p.readyAt||order.readyAt)}</strong></div><div><span>전달 {p.robotId||'—'}</span><strong>{p.handoffAt?formatTime(p.handoffAt):'픽업'}</strong></div></div><div className="sync-gap"><b>{p.gap===0?'도착시간 맞춤':p.gap===null?'매장 픽업':'준비 중'}</b><span>도착시간 차이</span><strong>{p.gap===null?'—':Math.ceil(p.gap)}분</strong></div><details className="sync-schedule"><summary>준비 일정 보기</summary><ol className="sync-timeline">{[[order.confirmedAt,'주문 완료'],[p.prepStart,'준비 시작'],[p.readyAt,'준비 완료'],[p.dispatchAt,'전달 출발'],[p.handoffAt,'도착 후 수령']].filter(([t])=>Number.isFinite(t)).map(([t,label])=><li key={label}><b>{formatTime(t)}</b><span>{label}</span></li>)}</ol></details>{order.syncEvents?.length>0&&<details><summary>도착 동기화 업데이트</summary>{order.syncEvents.map((e,i)=><p key={i}>{e}</p>)}</details>}</section>;}
