import React from 'react';
import OrbitSafety from './OrbitSafety.jsx';
import {MODES,formatTime} from './arrivalEngine.js';
export function MobilitySwitcher({journey,onChange}){return <div className="mobility-switcher" aria-label="이동수단 변경">{MODES.map(m=><button key={m.id} aria-pressed={journey.transportMode===m.id} onClick={()=>onChange(m.id)}>{m.id==='bike'?'바이크':m.name}</button>)}</div>;}
export function MobilityDetails({journey,onBike,onBoard,bikePreview,onBikePreview,compareBike,onCompareBike,bikeMap,onBikeRetry,onNavigationUpdate,onReroute}){const r=journey.route;if(journey.transportMode==='transit')return <section className="mobility-detail"><b>탑승 가능성이 높은 열차 기준</b><p>역까지 도보 {r.walkToStation}분 + 탑승 여유 {r.boardingBuffer}분</p><p>출발 시점 기준 · 2호선 · 다음 열차 {r.arrivals[0]}분 / 탑승 예정 {r.nextTrain}분</p><p>도보 → 열차 {r.ride}분 → 도보 {r.finalWalk}분</p><button className="arrival-secondary" disabled={r.boarded} onClick={onBoard}>{r.boarded?'열차 탑승 완료':'탑승 예정 열차에 탑승'}</button><small>Demo transit data · 경로와 열차 시뮬레이션</small></section>;
 if(journey.transportMode==='bike')return <OrbitSafety journey={journey} onSelect={onBike} compare={compareBike} onCompare={onCompareBike} bikeMap={bikeMap} onRetry={onBikeRetry} onNavigationUpdate={onNavigationUpdate} onReroute={onReroute}/>;
 if(journey.transportMode==='walk')return <section className="mobility-detail"><b>도보 {r.distanceKm.toFixed(1)} km</b><p>예상 속도 {r.speedKmh} km/h · 거리 기반 추정</p></section>;
 return <p className="data-note">도로 이동시간 추정 · 실시간 교통 미반영</p>;}
export function ArrivalSync({order,clock}){const p=order.sync;if(!p)return null;return <section className="sync-panel"><p className="step-label">ARRIVAL SYNC</p><h2>사람과 상품,<br/>같은 도착시간</h2><div className="sync-grid"><div><span>YOU</span><strong>{formatTime(order.arrival)}</strong></div><div><span>ORDER Ready</span><strong>{formatTime(p.readyAt||order.readyAt)}</strong></div><div><span>ROBOT {p.robotId||'—'}</span><strong>{p.handoffAt?formatTime(p.handoffAt):'픽업'}</strong></div></div><div className="sync-gap"><b>{p.gap===0?'SYNCED':p.gap===null?'매장 픽업':'준비 중'}</b><span>Arrival Gap</span><strong>{p.gap===null?'—':p.gap} min</strong></div><p>{p.robotId?`${p.robotId} ${p.status} · Dispatch in ${Math.max(0,Math.ceil((p.dispatchAt-clock)/60000))} min`:'로봇 예약 없이 매장 픽업'}</p><ol className="sync-timeline">{[[order.confirmedAt,'Order confirmed'],[p.prepStart,'Preparation starts'],[p.readyAt,'Product ready'],[p.dispatchAt,'Robot dispatch'],[p.handoffAt,'You + Product Arrive']].filter(([t])=>Number.isFinite(t)).map(([t,label])=><li key={label}><b>{formatTime(t)}</b><span>{label}</span></li>)}</ol>{order.syncEvents?.length>0&&<details open><summary>도착 동기화 업데이트</summary>{order.syncEvents.map((e,i)=><p key={i}>{e}</p>)}</details>}<small>Demo Robot State · 로봇 및 매장 준비 시뮬레이션</small></section>;}
