import React,{useEffect,useState} from 'react';
import {Map,Navigation,Car,Bike,TrainFront,Footprints,RefreshCw} from 'lucide-react';
import {loadKakao,routeURL} from './places.js';
import {loadNavi,navigateNavi} from './kakaoNavi.js';
import {api,apiBase} from './auth.js';
import {Vehicle} from './MobilityArt.jsx';
export const MODES=[['walk','도보',Footprints],['traffic','지하철',TrainFront],['car','자동차',Car],['bike','자전거',Bike]];
export function nearbyStation(kakao,area){return new Promise(resolve=>new kakao.maps.services.Places().categorySearch('SW8',(rows,status)=>resolve(status===kakao.maps.services.Status.OK?rows[0]?.place_name?.replace(/\s+\d.*호선.*$/,'')||'': ''),{location:new kakao.maps.LatLng(area.lat,area.lng),radius:2000,sort:kakao.maps.services.SortBy.DISTANCE,size:1}));}
export default function MobilityPanel({area,gps,kakaoKey,mode,onMode,onStart,onNotice,onInsights}){
 useEffect(()=>{const timer=setInterval(()=>setRefresh(n=>n+1),60000);return()=>clearInterval(timer);},[]);
 const [tab,setTab]=useState('map'),[data,setData]=useState(null),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let dead=false;const controller=new AbortController();setData(null);onInsights(null);if(!apiBase())return;setLoading(true);(async()=>{try{let station='';if(kakaoKey&&area.lat>37.4&&area.lat<37.75&&area.lng>126.7&&area.lng<127.3)station=await nearbyStation(await loadKakao(kakaoKey),area);const next=await api('/api/mobility?'+new URLSearchParams({station,lat:String(area.lat),lng:String(area.lng)}),{signal:controller.signal});if(!dead){setData(next);onInsights(next);}}catch{}finally{if(!dead)setLoading(false);}})();return()=>{dead=true;controller.abort();};},[area.lat,area.lng,kakaoKey,refresh]);
 async function openNavi(){try{await loadNavi(kakaoKey);navigateNavi(area);}catch(e){onNotice(e.message);}}
 return <section className="mobility-panel"><div className="mobility-heading"><span>어떻게 이동할까요?</span><button onClick={onStart}>당도 시작<ArrowIcon/></button></div><div className="mobility-modes">{MODES.map(([id,label,Icon])=><button key={id} aria-pressed={mode===id} className={mode===id?'active':''} onClick={()=>onMode(id)}>{id==='walk'?<Icon size={28}/>:<Vehicle kind={id==='traffic'?'train':id==='bike'?'bike':'car'}/>}<span>{label}</span></button>)}</div><div className="mobility-services" role="tablist" aria-label="이동 서비스">{[['map','카카오맵',Map],['navi','내비',Navigation],['taxi','카카오 T',Car],['bike','바이크',Bike]].map(([id,name,Icon])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}><Icon size={18}/>{name}</button>)}</div><div className="service-action">{tab==='map'?<a href={routeURL(area,gps,mode==='bike'?'bicycle':mode)} target="_blank" rel="noopener noreferrer">카카오맵 길 안내 열기<ArrowIcon/></a>:tab==='navi'?<button onClick={openNavi}>카카오내비 열기<ArrowIcon/></button>:<><a href="https://www.kakaomobility.com/service-kakaot" target="_blank" rel="noopener noreferrer">{tab==='taxi'?'카카오 T 서비스 열기':'카카오 T 바이크 안내 열기'}<ArrowIcon/></a><span>목적지 자동 전달은 제휴 연결 후 지원해요</span></>}</div><div className="arrival-intelligence"><div><TrainFront size={20}/><strong>도착지 교통</strong><button aria-label="교통 새로고침" onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={16}/></button></div>{loading?<p>교통 정보를 확인하고 있어요</p>:data?.subway?.available?<><p>다음 열차 평균 <b>{Math.ceil(data.subway.meanNextArrivalSeconds/60)}분</b></p><span>{data.subway.sampleCount}개 노선·방향의 현재 잔여시간 평균</span>{data.subway.next.slice(0,2).map((x,i)=><p key={i}>{x.destination}<b>{Math.ceil(x.seconds/60)}분</b></p>)}</>:<p>이 지역의 실시간 열차 정보가 아직 연결되지 않았어요</p>}{data?.crowd?.available&&<p>주변 지역 혼잡도 <b>{data.crowd.level}</b></p>}</div></section>;
}
function ArrowIcon(){return <span aria-hidden="true">↗</span>;}
