export const START_BALANCE = 246344;
export const destinations = [{id:'seongsu',name:'성수역 3번 출구',address:'서울 성동구 아차산로 100',short:'성수역'}, {id:'forest',name:'서울숲 정문',address:'서울 성동구 뚝섬로 273',short:'서울숲'}, {id:'gwang',name:'광화문역 2번 출구',address:'서울 종로구 세종대로 172',short:'광화문역'}];
export const offers = [
 {id:'coffee',dest:'seongsu',merchant:'오후커피 성수',product:'아이스 아메리카노',category:'카페',walk:2,price:4500,discount:1500,reward:150,stock:8,type:'coffee',label:'도착 전 주문하면',address:'서울 성동구 연무장길 18',description:'고소한 원두로 내린 아메리카노. 도착하면 바로 가져가세요.'},
 {id:'bakery',dest:'seongsu',merchant:'성수 베이크',product:'소금빵 2개 세트',category:'베이커리',walk:4,price:7000,discount:1000,reward:300,stock:5,type:'bread',label:'갓 구운 소금빵',address:'서울 성동구 연무장길 28',description:'바삭한 겉면과 촉촉한 속. 소금빵 두 개를 함께 준비해 드려요.'},
 {id:'meal',dest:'seongsu',merchant:'그린테이블 성수',product:'치킨 샐러드',category:'식사',walk:5,price:12000,discount:2000,reward:500,stock:4,type:'salad',label:'가볍게 한 끼',address:'서울 성동구 성수이로 42',description:'신선한 채소와 구운 닭가슴살. 드레싱은 따로 담아 드려요.'},
 {id:'forest-coffee',dest:'forest',merchant:'숲길커피',product:'아이스 라떼',category:'카페',walk:3,price:5500,discount:1500,reward:200,stock:6,type:'coffee',label:'산책 전 한 잔',address:'서울 성동구 서울숲2길 8',description:'부드러운 우유와 진한 에스프레소. 서울숲 입구에서 픽업하세요.'},
 {id:'forest-bread',dest:'forest',merchant:'숲길 베이커리',product:'크루아상 세트',category:'베이커리',walk:4,price:8000,discount:2000,reward:300,stock:3,type:'bread',label:'산책에 챙겨가세요',address:'서울 성동구 서울숲2길 12',description:'버터 크루아상 두 개를 담은 세트예요.'}
];
export const campaign={id:'arrival-week',name:'성수 도착 위크',sponsor:'성수 위크 · 가상 브랜드',operatingFee:500000,performanceFee:1000,budget:1000000,target:100,minimumPurchase:3000};
export function funding(offer){return ['coffee','forest-coffee'].includes(offer.id)?'brand':'merchant';}
export function settlement(offer){const sponsored=funding(offer)==='brand',customerPayment=offer.price-offer.discount,brandSupport=sponsored?offer.discount:0,processingFee=Math.round(customerPayment*.02),platformFee=sponsored?0:Math.round(customerPayment*.05),merchantRewardCost=sponsored?0:offer.reward;return {funding:sponsored?'brand':'merchant',sponsor:sponsored?campaign.sponsor:null,customerPayment,brandSupport,merchantDiscount:sponsored?0:offer.discount,processingFee,platformFee,merchantRewardCost,brandRewardCost:sponsored?offer.reward:0,merchantSettlement:customerPayment+brandSupport-processingFee-platformFee-merchantRewardCost,performanceFee:sponsored?campaign.performanceFee:0};}
export const initialState = () => ({version:2,trip:{id:crypto.randomUUID(),dest:'seongsu',eta:8},orders:[],balance:START_BALANCE,points:0});
export function eligible(offer, trip, orders){const active=orders.filter(o=>o.status!=='취소 완료');return offer.dest===trip.dest && trip.eta>=0 && trip.eta<=15 && active.filter(o=>o.offerId===offer.id).length<offer.stock && !active.some(o=>o.tripId===trip.id&&o.offerId===offer.id);}
export function quote(offer){return {original:offer.price,discount:offer.discount,total:offer.price-offer.discount,reward:offer.reward};}
export function completePayment(state,offer,{id=crypto.randomUUID(),now=new Date().toISOString()}={}){
 if(state.orders.some(o=>o.id===id)) return state;
 if(!eligible(offer,state.trip,state.orders)) throw new Error('지금은 이 혜택을 사용할 수 없어요.');
 const amounts=quote(offer); if(state.balance<amounts.total) throw new Error('페이머니 잔액이 부족해요.');
 const bill=settlement(offer);if(bill.funding==='brand'){const reserved=state.orders.filter(o=>o.status!=='취소 완료'&&o.billing?.funding==='brand').reduce((n,o)=>n+o.billing.brandSupport+o.billing.brandRewardCost,0);if(reserved+bill.brandSupport+bill.brandRewardCost>campaign.budget)throw new Error('캠페인 혜택 예산을 모두 사용했어요.');}
 const order={id,offerId:offer.id,tripId:state.trip.id,merchant:offer.merchant,product:offer.product,type:offer.type,dest:state.trip.dest,eta:state.trip.eta,...amounts,billing:bill,createdAt:now,pickupCode:String(1000+(state.orders.length+1)*37),status:'준비 중'};
 return {...state,balance:state.balance-amounts.total,points:state.points+amounts.reward,orders:[order,...state.orders]};
}
export function merchantStats(orders,merchant){const rows=orders.filter(o=>o.merchant===merchant),active=rows.filter(o=>o.status!=='취소 완료');return {payments:12+active.length,revenue:51600+active.reduce((n,o)=>n+o.total,0),discount:18000+active.reduce((n,o)=>n+o.discount,0),points:1800+active.reduce((n,o)=>n+o.reward,0),views:86,selected:24+active.length,rows};}
export function cancelOrder(state,id){const order=state.orders.find(o=>o.id===id);if(!order)throw new Error('주문을 찾을 수 없어요.');if(order.status==='취소 완료')return state;if(order.status==='픽업 완료')throw new Error('픽업 완료 주문은 취소할 수 없어요.');return {...state,balance:state.balance+order.total,points:state.points-order.reward,orders:state.orders.map(o=>o.id===id?{...o,status:'취소 완료'}:o)};}
export function advanceOrder(state,id){const row=state.orders.find(o=>o.id===id);if(!row||!['준비 중','픽업 가능'].includes(row.status))throw new Error('변경할 수 없는 주문 상태예요.');return {...state,orders:state.orders.map(o=>o.id===id?{...o,status:o.status==='준비 중'?'픽업 가능':'픽업 완료'}:o)};}
export function campaignStats(orders){const rows=orders.filter(o=>o.billing?.funding==='brand'),active=rows.filter(o=>o.status!=='취소 완료'),confirmed=active.filter(o=>o.status==='픽업 완료'&&o.total>=campaign.minimumPurchase);return {rows,active,confirmed,benefitReserved:active.reduce((n,o)=>n+o.billing.brandSupport+o.billing.brandRewardCost,0),benefitUsed:confirmed.reduce((n,o)=>n+o.billing.brandSupport+o.billing.brandRewardCost,0),performanceFee:confirmed.reduce((n,o)=>n+o.billing.performanceFee,0),operatingFee:campaign.operatingFee,merchantSettlement:confirmed.reduce((n,o)=>n+o.billing.merchantSettlement,0)};}
export function restoreState(raw){try{const s=JSON.parse(raw);if([1,2].includes(s?.version)&&Array.isArray(s.orders)&&Number.isFinite(s.balance)&&Number.isFinite(s.points)&&destinations.some(d=>d.id===s.trip?.dest)&&Number.isFinite(s.trip.eta)&&typeof s.trip.id==='string'){if(!s.orders.every(o=>offers.some(f=>f.id===o.offerId)&&typeof o.id==='string'&&Number.isFinite(o.total)&&Number.isFinite(o.reward)))return initialState();return {...s,version:2,orders:s.orders.map(o=>({...o,billing:o.billing??settlement(offers.find(f=>f.id===o.offerId))}))};}}catch{}return initialState();}
