import React,{useEffect,useRef,useState} from 'react';
import {navigationProgress} from './orbit/navigationEngine.js';
export default function OrbitNavigation({route,onUpdate,onReroute}){const [active,setActive]=useState(false),[voice,setVoice]=useState(false),[state,setState]=useState(null),[error,setError]=useState('');const watch=useRef(),latest=useRef({route,onUpdate,onReroute,voice}),rerouteAt=useRef(0),spoken=useRef('');latest.current={route,onUpdate,onReroute,voice};
 const stop=()=>{if(watch.current!==undefined)navigator.geolocation?.clearWatch(watch.current);watch.current=undefined;setActive(false);window.speechSynthesis?.cancel();};
 useEffect(()=>()=>{if(watch.current!==undefined)navigator.geolocation?.clearWatch(watch.current);window.speechSynthesis?.cancel();},[]);
 useEffect(()=>{setState(null);spoken.current='';},[route.id,route.path]);
 function start(){if(!navigator.geolocation){setError('GPS를 지원하지 않는 환경이에요. 경로 안내 목록을 확인해 주세요.');return;}setError('');setActive(true);watch.current=navigator.geolocation.watchPosition(p=>{const position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};if(position.accuracy>80){setError('GPS 오차가 커요. 위치가 안정되면 안내를 이어갑니다.');return;}setError('');const r=latest.current.route,next=navigationProgress(r,position);setState(next);if(!next)return;if(next.offRoute){if(Date.now()-rerouteAt.current>25000){rerouteAt.current=Date.now();latest.current.onReroute(position);}return;}latest.current.onUpdate(position,next);if(latest.current.voice&&next.nextDistance<=300&&next.nextInstruction!==spoken.current&&window.speechSynthesis){spoken.current=next.nextInstruction;const u=new SpeechSynthesisUtterance(`${next.nextDistance}미터 앞, ${next.nextInstruction}`);u.lang='ko-KR';window.speechSynthesis.speak(u);}},()=>{setError('위치 권한을 확인해 주세요. GPS 없이도 경로 안내 목록을 볼 수 있어요.');stop();},{enableHighAccuracy:true,maximumAge:5000,timeout:12000});}
 return <section className="orbit-navigation"><b>ORBIT 경로 안내</b>{active?<><p role="status">{state?state.offRoute?'경로를 벗어나 다시 찾고 있어요':`${state.nextDistance}m 앞 · ${state.nextInstruction}`:'GPS 위치를 확인하고 있어요'}</p>{state&&<p>{(state.remainingMeters/1000).toFixed(1)} km · 약 {Math.ceil(state.remainingSeconds/60)}분 남음</p>}<button className="arrival-secondary" onClick={stop}>안내 종료</button></>:<button className="arrival-secondary" onClick={start}>GPS로 경로 안내 시작</button>}<label className="orbit-compare-toggle"><input type="checkbox" checked={voice} onChange={e=>setVoice(e.target.checked)}/>음성 안내</label>{error&&<p className="data-note" role="status">{error}</p>}<small>원본 ORBIT의 GPS 진행·경로 이탈 재탐색 · 예상 시간은 경로 기반 추정</small></section>;
}
