import React,{useState} from 'react';
import {ArrowLeft,MapPin,Gift,Check,ShieldCheck} from 'lucide-react';
import './payment-page.css';
export default function PaymentPage({place,places,benefits,onBack}){
 const options=[...new Map([...(place?.id?[place]:[]),...places].map(p=>[p.id,p])).values()];
 const [id,setId]=useState(place?.id||''),[item,setItem]=useState(''),[amount,setAmount]=useState('');
 const merchant=options.find(p=>p.id===id),gift=merchant&&benefits[merchant.id],total=/^\d{1,8}$/.test(amount)?Number(amount):0;
 return <main className="payment-page"><div className="pp-shell"><header><button aria-label="결제 페이지 닫기" onClick={onBack}><ArrowLeft size={23}/></button><h1>결제</h1><span>pay</span></header><section className="pp-heading"><small>DANGDO</small><h2>도착의 즐거움을<br/>결제로 이어가세요</h2></section><section className="pp-card"><h3>결제 지점</h3><label>지점 선택<select aria-label="결제 지점" value={id} onChange={e=>setId(e.target.value)}><option value="">결제할 지점을 선택하세요</option>{options.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{merchant&&<p className="pp-address"><MapPin size={16}/>{merchant.address||merchant.name}</p>}{!options.length&&<p className="pp-note">주변 식당을 찾은 후 결제할 지점을 선택하세요.</p>}</section><section className="pp-card"><h3>주문 내용</h3><label>상품 또는 메뉴<input aria-label="주문 내용" value={item} onChange={e=>setItem(e.target.value)} maxLength={100} placeholder="매장에서 확인한 메뉴를 입력하세요"/></label><label>결제 금액<div className="pp-amount"><input aria-label="결제 금액" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,'').slice(0,8))} inputMode="numeric" placeholder="금액 입력"/><span>원</span></div></label></section>{gift&&<section className="pp-gift"><Gift size={27}/><div><span>이 지점의 사은품</span><h3>{gift.name}</h3><p>{gift.terms||'제공 조건과 재고는 지점에서 확인하세요.'}</p></div></section>}<section className="pp-card"><h3>결제수단</h3><div className="pp-method"><b>pay</b><span>카카오페이</span><Check size={21}/></div></section><section className="pp-total"><span>총 결제금액</span><strong>{total?total.toLocaleString('ko-KR')+'원':'금액을 입력하세요'}</strong></section><div className="pp-bottom"><button disabled aria-label="결제하기">{total?total.toLocaleString('ko-KR')+'원 ':''}결제하기</button><p><ShieldCheck size={15}/>카카오페이 승인 연결 후 결제할 수 있어요.</p><small>입력한 주문은 매장에 전송되지 않습니다.</small></div></div></main>;
}
export function BenefitEditor({places,benefits,onSave,Dialog,onClose}){
 const [id,setId]=useState(places[0]?.id||''),[name,setName]=useState(benefits[places[0]?.id]?.name||''),[terms,setTerms]=useState(benefits[places[0]?.id]?.terms||'');
 function select(v){setId(v);setName(benefits[v]?.name||'');setTerms(benefits[v]?.terms||'');}
 return <Dialog title="지점별 사은품 설정" onClose={onClose}><form className="dialog-body benefit-editor" onSubmit={e=>{e.preventDefault();if(id&&name.trim()){onSave(id,{name:name.trim(),terms:terms.trim()});onClose();}}}><p>사은품을 제공할 지점과 내용을 등록하세요. 입력한 정보는 이 브라우저에 저장됩니다.</p><label>제공 지점<select required aria-label="사은품 제공 지점" value={id} onChange={e=>select(e.target.value)}><option value="">지점 선택</option>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>사은품 이름<input required aria-label="사은품 이름" value={name} onChange={e=>setName(e.target.value)} maxLength={80} placeholder="제공할 사은품"/></label><label>증정 조건<input aria-label="사은품 증정 조건" value={terms} onChange={e=>setTerms(e.target.value)} maxLength={200} placeholder="금액, 기간, 수량 등 제공 조건"/></label><button className="dd-primary" disabled={!id||!name.trim()}>등록</button>{benefits[id]&&<button type="button" className="dd-secondary" onClick={()=>{onSave(id,null);onClose();}}>이 지점 사은품 제거</button>}{!places.length&&<p>먼저 주변 식당을 검색해 주세요.</p>}</form></Dialog>;
}
