export const AREAS = [
  {name:'KAIST',lat:36.3707,lng:127.3624},
  {name:'성수역',lat:37.5446,lng:127.0559},
  {name:'서울숲',lat:37.5445,lng:127.0374},
  {name:'전주 한옥마을',lat:35.8151,lng:127.1530},
];
const CUISINES = {korean:'한식',japanese:'일식',chinese:'중식',italian:'이탈리안',pizza:'피자',burger:'버거',chicken:'치킨',sandwich:'샌드위치',coffee_shop:'커피',asian:'아시아 음식',vietnamese:'베트남 음식',thai:'태국 음식',indian:'인도 음식',noodle:'면 요리',noodles:'면 요리',barbecue:'구이',seafood:'해산물',sushi:'초밥',ramen:'라멘',regional:'지역 음식',international:'세계 음식',steak_house:'스테이크',mexican:'멕시코 음식'};
export function distance(a,b){const rad=Math.PI/180,dl=(b.lat-a.lat)*rad,dn=(b.lng-a.lng)*rad;const h=Math.sin(dl/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dn/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function distanceLabel(m){return m>=1000?`${(m/1000).toFixed(1)}km`:`${Math.round(m/10)*10}m`;}
export function normalizeOSM(elements,center){return elements.flatMap(e=>{const t=e.tags||{},lat=e.lat??e.center?.lat,lng=e.lon??e.center?.lon,name=t['name:ko']||t.name;if(!name||!Number.isFinite(lat)||!Number.isFinite(lng))return [];const cuisine=(t.cuisine||'').split(';').filter(Boolean).map(x=>CUISINES[x]||x).join('   ');const kind=t.amenity==='cafe'?'카페':t.amenity==='fast_food'?'간편식':'음식점';return [{id:`osm-${e.type}-${e.id}`,name,lat,lng,category:cuisine||kind,kind,address:t['addr:full']||[t['addr:city'],t['addr:street'],t['addr:housenumber']].filter(Boolean).join(' '),phone:t.phone||t['contact:phone']||'',hours:t.opening_hours||'',source:'OpenStreetMap',distance:distance(center,{lat,lng}),url:`https://www.openstreetmap.org/${e.type}/${e.id}`}];}).sort((a,b)=>a.distance-b.distance).filter((p,i,all)=>all.findIndex(o=>o.name===p.name&&distance(o,p)<40)===i).slice(0,60);}
const cache=new Map();
export async function nearbyOSM(center,radius,signal){
 const key=`${center.lat.toFixed(4)},${center.lng.toFixed(4)},${radius}`;
 if(cache.has(key)&&Date.now()-cache.get(key).time<300000)return cache.get(key).rows;
 const query=`[out:json][timeout:20];nwr["amenity"~"^(restaurant|cafe|fast_food)$"]["name"](around:${radius},${center.lat},${center.lng});out center tags;`;
 let last;
 for(const endpoint of ['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter']){
  if(signal?.aborted)throw new DOMException('Aborted','AbortError');
  try{const response=await fetch(endpoint,{method:'POST',body:new URLSearchParams({data:query}),signal:AbortSignal.any([signal,AbortSignal.timeout(26000)].filter(Boolean))});if(!response.ok)throw new Error(`검색 서버 응답 ${response.status}`);const json=await response.json();if(json.remark||!Array.isArray(json.elements))throw new Error('검색 서버가 혼잡해요');const rows=normalizeOSM(json.elements,center);cache.set(key,{time:Date.now(),rows});return rows;}catch(e){if(signal?.aborted)throw e;last=e;}
 }
 throw last||new Error('검색 서버에 연결하지 못했어요');
}
let kakaoPromise;
export function loadKakao(key){if(window.kakao?.maps?.services)return Promise.resolve(window.kakao);if(kakaoPromise)return kakaoPromise;kakaoPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>{script.remove();kakaoPromise=null;reject(new Error('카카오 지도 연결 시간 초과. 키와 등록 도메인을 확인해 주세요.'));},15000);script.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(key)}&autoload=false&libraries=services`;script.onload=()=>{if(!window.kakao?.maps){clearTimeout(timer);kakaoPromise=null;reject(new Error('JavaScript 키와 카카오맵 사용 설정을 확인해 주세요.'));return;}window.kakao.maps.load(()=>{clearTimeout(timer);resolve(window.kakao);});};script.onerror=()=>{clearTimeout(timer);script.remove();kakaoPromise=null;reject(new Error('카카오 지도를 불러오지 못했어요.'));};document.head.append(script);});return kakaoPromise;}
export function nearbyKakao(kakao,center,radius){const ps=new kakao.maps.services.Places();return Promise.all(['FD6','CE7'].map(category=>new Promise((resolve,reject)=>{ps.categorySearch(category,(data,status)=>{if(status===kakao.maps.services.Status.ZERO_RESULT)return resolve([]);if(status!==kakao.maps.services.Status.OK)return reject(new Error('카카오 장소 검색에 실패했어요'));resolve(data.map(p=>({id:`kakao-${p.id}`,name:p.place_name,lat:Number(p.y),lng:Number(p.x),category:p.category_name.split(' > ').slice(1).join('   ')||'음식점',kind:category==='CE7'?'카페':'음식점',address:p.road_address_name||p.address_name,phone:p.phone,hours:'',source:'카카오맵',url:p.place_url,distance:distance(center,{lat:Number(p.y),lng:Number(p.x)})})));},{location:new kakao.maps.LatLng(center.lat,center.lng),radius,sort:kakao.maps.services.SortBy.DISTANCE,size:15});}))).then(groups=>groups.flat().sort((a,b)=>a.distance-b.distance));}
export async function searchArea(query,key,signal){if(key){const kakao=await loadKakao(key);return new Promise((resolve,reject)=>new kakao.maps.services.Places().keywordSearch(query,(data,status)=>{if(status===kakao.maps.services.Status.ZERO_RESULT)return resolve([]);if(status!==kakao.maps.services.Status.OK)return reject(new Error('장소를 찾지 못했어요'));resolve(data.slice(0,5).map(p=>({name:p.place_name,address:p.road_address_name||p.address_name,lat:Number(p.y),lng:Number(p.x)})));}));}const res=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&accept-language=ko&q=${encodeURIComponent(query)}`,{signal});if(!res.ok)throw new Error('장소 검색이 지연되고 있어요');const data=await res.json();return data.map(p=>({name:p.name||p.display_name.split(',')[0],address:p.display_name,lat:Number(p.lat),lng:Number(p.lon)}));}
export function routeURL(place,origin,mode='walk'){const to=`${encodeURIComponent(place.name)},${place.lat},${place.lng}`;return origin?`https://map.kakao.com/link/by/${mode}/${encodeURIComponent(origin.name||'출발지')},${origin.lat},${origin.lng}/${to}`:`https://map.kakao.com/link/to/${to}`;}
export function placeText(p){return `${p.name}. ${p.category}. ${p.kind}.`}
export function rankPlaces(places,scores){return places.map((p,i)=>({...p,similarity:scores[i],score:0.85*scores[i]+0.15*Math.exp(-p.distance/1000)})).sort((a,b)=>b.score-a.score);}
